### PR TITLE
[lang] Annotate constants with dtype without casting.

### LINKED ISSUE #4210: False warnings on unsigned integer overflow
**Describe the bug**
Weird warnings about unsigned integer exceeding the range

**To Reproduce**

```py
import taichi as ti

ti.init(arch=ti.gpu)

@ti.kernel
def u32_test():
    x: ti.u32 = 2891336453
    print("x = ", x)

u32_test()
```

**Log/Screenshots**
```
[Taichi] version 0.8.11, llvm 10.0.0, commit 9d0973e5, win, python 3.7.8
[Taichi] Starting on arch=cuda
[W 02/04/22 20:57:53.169 24856] [impl.py:_clamp_unsigned_to_range@395] Constant 2891336453 has exceeded the range of 32 int, clamped to -1403630843
x =  2891336453
```

**Additional comments**
It wasn't actually clamped and kernel works correctly as far as I can tell, so basically it's just about false warnings

### PR DESCRIPTION
**Pull request by ailzhang**
Fixes #4210

This PR also simplifies the clamping logic by:
1. Make sure constant is valid in range of specified dtype.
2. Always use the widest int64/float64 to communicate between python and C++ and
converts it to the specified dtype in C++. This is just to avoid
handling each dtype on both python and C++ side.

We might consider further improve it by moving this logic from python to C++ in the future and this PR made it a step closer.

Related issue = #

### CODE REVIEW

File: taichi/python/export_lang.cpp [hunk 1]
```diff
@@ -777,10 +778,11 @@ void export_lang(py::module &m) {
 
   m.def("make_rand_expr", Expr::make<RandExpression, const DataType &>);
 
-  m.def("make_const_expr_i32", Expr::make<ConstExpression, int32>);
-  m.def("make_const_expr_i64", Expr::make<ConstExpression, int64>);
-  m.def("make_const_expr_f32", Expr::make<ConstExpression, float32>);
-  m.def("make_const_expr_f64", Expr::make<ConstExpression, float64>);
+  m.def("make_const_expr_ip",
```
Comment (lin-hitonami) [inline taichi/python/export_lang.cpp:781]: What does `ip` stand for? IIUC `fp` is the acronym of floating point, and the acronym of integer should be `int`?

File: python/taichi/lang/expr.py [hunk 2]
```diff
@@ -33,7 +33,7 @@ def __init__(self, *args, tb=None):
                         arg = arg.dtype.type(arg)
                     except:
```
Comment (lin-hitonami) [inline python/taichi/lang/expr.py:34]: I don't know why this try-except block exists, can we remove it?

File: python/taichi/lang/impl.py [hunk 3]
```diff
@@ -381,58 +382,45 @@ def get_runtime():
...
-        assert False
-    else:
-        raise TaichiTypeError(
-            f'Invalid constant scalar data type: {type(val)}')
+        constant_dtype = pytaichi.default_ip if dtype is None else dtype
+        _check_in_range(to_numpy_type(constant_dtype), val)
+        return Expr(
+            _ti_core.make_const_expr_ip(
+                constant_dtype, _clamp_unsigned_to_range(np.int64, val)))
+    if isinstance(val, (float, np.floating, np.ndarray)):
```
Comment (lin-hitonami) [inline python/taichi/lang/impl.py:420]: IIUC, if we remove the try-except block in `Expr.__init__`, we can remove `np.ndarray` here as well.

File: taichi/python/export_lang.cpp (hunk 1 above)
Comment (ailzhang) [reply taichi/python/export_lang.cpp]: good point, I don't know what ip stands for either but copied from default_ip lol. Changed to int here ;)

**Review by lin-hitonami — APPROVED** [review]
LGTM!
