### PR TITLE
[Bug] [opt] Fix compilation crash when there is a container statement after an unconditional continue

### LINKED ISSUE #1297: [Bug] [ir] a simple kernel with multiple continue fails to compile
sample 1:
```py
import taichi as ti

#ti.core.toggle_advanced_optimization(False) # OK with this line

@ti.kernel
def func():
    for i in range(1):
        if 0:
            if 0:
                continue
        if 0:
            if 0:
                continue

func()
```
obtains
```
[Taichi] mode=development
[Taichi] preparing sandbox at /tmp/taichi-ht5kpvcd
[Taichi] <dev mode>, supported archs: [cpu, cuda, opengl], llvm 8.0.1, commit 04c58526, python 3.8.2
[E 06/21/20 18:48:42.522] [verify.cpp:visit@54] stmt_list->parent == current_block


***********************************
* Taichi Compiler Stack Traceback *                                                          
***********************************                                                          
/tmp/taichi-ht5kpvcd/taichi_core.so: taichi::Logger::error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)                                  
/tmp/taichi-ht5kpvcd/taichi_core.so: taichi::lang::IRVerifier::visit(taichi::lang::Block*)   
/tmp/taichi-ht5kpvcd/taichi_core.so: taichi::lang::BasicStmtVisitor::visit(taichi::lang::IfStmt*)                                                                                         
/tmp/taichi-ht5kpvcd/taichi_core.so: taichi::lang::IRVerifier::visit(taichi::lang::Block*)   
/tmp/taichi-ht5kpvcd/taichi_core.so: taichi::lang::BasicStmtVisitor::visit(taichi::lang::IfStmt*)                                                                                         
/tmp/taichi-ht5kpvcd/taichi_core.so: taichi::lang::IRVerifier::visit(taichi::lang::Block*)   
/tmp/taichi-ht5kpvcd/taichi_core.so: taichi::lang::IRVerifier::visit(taichi::lang::Block*)   
/tmp/taichi-ht5kpvcd/taichi_core.so: taichi::lang::irpass::analysis::verify(taichi::lang::IRNode*)                                                                                        
/tmp/taichi-ht5kpvcd/taichi_core.so: taichi::lang::irpass::compile_to_offloads(taichi::lang::IRNode*, taichi::lang::CompileConfig const&, bool, bool, bool, bool, bool)
/tmp/taichi-ht5kpvcd/taichi_core.so: taichi::lang::Kernel::lower(bool)
/tmp/taichi-ht5kpvcd/taichi_core.so: taichi::lang::Program::compile(taichi::lang::Kernel&)
/tmp/taichi-ht5kpvcd/taichi_core.so: taichi::lang::Kernel::compile()
/tmp/taichi-ht5kpvcd/taichi_core.so: taichi::lang::Kernel::operator()()
/tmp/taichi-ht5kpvcd/taichi_core.so(+0x7cd764) [0x7f2d2b438764]
/tmp/taichi-ht5kpvcd/taichi_core.so(+0x730c86) [0x7f2d2b39bc86]
/usr/lib/libpython3.8.so.1.0: PyCFunction_Call
/usr/lib/libpython3.8.so.1.0: _PyObject_MakeTpCall
/usr/lib/libpython3.8.so.1.0(+0xfeb1d) [0x7f2d3b101b1d]
/usr/lib/libpython3.8.so.1.0: PyObject_Call
/usr/lib/libpython3.8.so.1.0(+0xb121b) [0x7f2d3b0b421b]
/usr/lib/libpython3.8.so.1.0: _PyObject_MakeTpCall
/usr/lib/libpython3.8.so.1.0: _PyEval_EvalFrameDefault
/usr/lib/libpython3.8.so.1.0: _PyEval_EvalCodeWithName
/usr/lib/libpython3.8.so.1.0: _PyFunction_Vectorcall
/usr/lib/libpython3.8.so.1.0: PyObject_Call
/usr/lib/libpython3.8.so.1.0: _PyEval_EvalFrameDefault
/usr/lib/libpython3.8.so.1.0: _PyEval_EvalCodeWithName
/usr/lib/libpython3.8.so.1.0: _PyFunction_Vectorcall
/usr/lib/libpython3.8.so.1.0: _PyObject_FastCallDict
/usr/lib/libpython3.8.so.1.0: _PyObject_Call_Prepend
/usr/lib/libpython3.8.so.1.0(+0x23d0e9) [0x7f2d3b2400e9]
/usr/lib/libpython3.8.so.1.0: PyObject_Call
/usr/lib/libpython3.8.so.1.0: _PyEval_EvalFrameDefault
/usr/lib/libpython3.8.so.1.0: _PyEval_EvalCodeWithName
/usr/lib/libpython3.8.so.1.0: _PyFunction_Vectorcall
/usr/lib/libpython3.8.so.1.0: _PyEval_EvalFrameDefault
/usr/lib/libpython3.8.so.1.0: _PyEval_EvalCodeWithName
/usr/lib/libpython3.8.so.1.0: PyEval_EvalCode
/usr/lib/libpython3.8.so.1.0(+0x2668c8) [0x7f2d3b2698c8]
/usr/lib/libpython3.8.so.1.0(+0x26aba3) [0x7f2d3b26dba3]
/usr/lib/libpython3.8.so.1.0: PyRun_FileExFlags
/usr/lib/libpython3.8.so.1.0: PyRun_SimpleFileExFlags
/usr/lib/libpython3.8.so.1.0: Py_RunMain
/usr/lib/libpython3.8.so.1.0: Py_BytesMain
/usr/lib/libc.so.6: __libc_start_main
python(_start+0x2e) [0x562d75bd605e]

Internal Error occurred, check this page for possible solutions:
https://taichi.readthedocs.io/en/stable/install.html#troubleshooting
Traceback (most recent call last):
  File "multiple_continue.py", line 15, in <module>
    func()
  File "/home/bate/Develop/taichi/python/taichi/lang/kernel.py", line 527, in wrapped
    return primal(*args, **kwargs)
  File "/home/bate/Develop/taichi/python/taichi/lang/kernel.py", line 459, in __call__
    return self.compiled_functions[key](*args)
  File "/home/bate/Develop/taichi/python/taichi/lang/kernel.py", line 423, in func__
    t_kernel()
RuntimeError: [verify.cpp:visit@54] stmt_list->parent == current_block
```

sample 2:
```py
import taichi as ti

#ti.core.toggle_advanced_optimization(False) # OK with this line

@ti.kernel
def func():
    for i in range(1):
        if 0:
            if 0:
                continue
        if 0:
            continue

func()
```
obtains
```
[Taichi] mode=development
[Taichi] preparing sandbox at /tmp/taichi-ctsxljpi
[Taichi] <dev mode>, supported archs: [cpu, cuda, opengl], llvm 8.0.1, commit 04c58526, python 3.8.2
[E 06/21/20 18:49:00.135] [verify.cpp:basic_verify@40] stmt 8 cannot have operand 7.


***********************************
* Taichi Compiler Stack Traceback *                                                          
***********************************                                                          
/tmp/taichi-ctsxljpi/taichi_core.so: taichi::Logger::error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)                                  
/tmp/taichi-ctsxljpi/taichi_core.so: taichi::lang::IRVerifier::basic_verify(taichi::lang::Stmt*)                                                                                          
/tmp/taichi-ctsxljpi/taichi_core.so: taichi::lang::BasicStmtVisitor::visit(taichi::lang::IfStmt*)                                                                                         
/tmp/taichi-ctsxljpi/taichi_core.so: taichi::lang::IRVerifier::visit(taichi::lang::Block*)   
/tmp/taichi-ctsxljpi/taichi_core.so: taichi::lang::BasicStmtVisitor::visit(taichi::lang::IfStmt*)                                                                                         
/tmp/taichi-ctsxljpi/taichi_core.so: taichi::lang::IRVerifier::visit(taichi::lang::Block*)   
/tmp/taichi-ctsxljpi/taichi_core.so: taichi::lang::IRVerifier::visit(taichi::lang::Block*)   
/tmp/taichi-ctsxljpi/taichi_core.so: taichi::lang::irpass::analysis::verify(taichi::lang::IRNode*)                                                                                        
/tmp/taichi-ctsxljpi/taichi_core.so: taichi::lang::irpass::compile_to_offloads(taichi::lang::IRNode*, taichi::lang::CompileConfig const&, bool, bool, bool, bool, bool)
/tmp/taichi-ctsxljpi/taichi_core.so: taichi::lang::Kernel::lower(bool)
/tmp/taichi-ctsxljpi/taichi_core.so: taichi::lang::Program::compile(taichi::lang::Kernel&)
/tmp/taichi-ctsxljpi/taichi_core.so: taichi::lang::Kernel::compile()
/tmp/taichi-ctsxljpi/taichi_core.so: taichi::lang::Kernel::operator()()
/tmp/taichi-ctsxljpi/taichi_core.so(+0x7cd764) [0x7ff6d3a76764]
/tmp/taichi-ctsxljpi/taichi_core.so(+0x730c86) [0x7ff6d39d9c86]
/usr/lib/libpython3.8.so.1.0: PyCFunction_Call
/usr/lib/libpython3.8.so.1.0: _PyObject_MakeTpCall
/usr/lib/libpython3.8.so.1.0(+0xfeb1d) [0x7ff6e373fb1d]
/usr/lib/libpython3.8.so.1.0: PyObject_Call
/usr/lib/libpython3.8.so.1.0(+0xb121b) [0x7ff6e36f221b]
/usr/lib/libpython3.8.so.1.0: _PyObject_MakeTpCall
/usr/lib/libpython3.8.so.1.0: _PyEval_EvalFrameDefault
/usr/lib/libpython3.8.so.1.0: _PyEval_EvalCodeWithName
/usr/lib/libpython3.8.so.1.0: _PyFunction_Vectorcall
/usr/lib/libpython3.8.so.1.0: PyObject_Call
/usr/lib/libpython3.8.so.1.0: _PyEval_EvalFrameDefault
/usr/lib/libpython3.8.so.1.0: _PyEval_EvalCodeWithName
/usr/lib/libpython3.8.so.1.0: _PyFunction_Vectorcall
/usr/lib/libpython3.8.so.1.0: _PyObject_FastCallDict
/usr/lib/libpython3.8.so.1.0: _PyObject_Call_Prepend
/usr/lib/libpython3.8.so.1.0(+0x23d0e9) [0x7ff6e387e0e9]
/usr/lib/libpython3.8.so.1.0: PyObject_Call
/usr/lib/libpython3.8.so.1.0: _PyEval_EvalFrameDefault
/usr/lib/libpython3.8.so.1.0: _PyEval_EvalCodeWithName
/usr/lib/libpython3.8.so.1.0: _PyFunction_Vectorcall
/usr/lib/libpython3.8.so.1.0: _PyEval_EvalFrameDefault
/usr/lib/libpython3.8.so.1.0: _PyEval_EvalCodeWithName
/usr/lib/libpython3.8.so.1.0: PyEval_EvalCode
/usr/lib/libpython3.8.so.1.0(+0x2668c8) [0x7ff6e38a78c8]
/usr/lib/libpython3.8.so.1.0(+0x26aba3) [0x7ff6e38abba3]
/usr/lib/libpython3.8.so.1.0: PyRun_FileExFlags
/usr/lib/libpython3.8.so.1.0: PyRun_SimpleFileExFlags
/usr/lib/libpython3.8.so.1.0: Py_RunMain
/usr/lib/libpython3.8.so.1.0: Py_BytesMain
/usr/lib/libc.so.6: __libc_start_main
python(_start+0x2e) [0x555d6faf705e]

Internal Error occurred, check this page for possible solutions:
https://taichi.readthedocs.io/en/stable/install.html#troubleshooting
Traceback (most recent call last):
  File "multiple_continue.py", line 14, in <module>
    func()
  File "/home/bate/Develop/taichi/python/taichi/lang/kernel.py", line 527, in wrapped
    return primal(*args, **kwargs)
  File "/home/bate/Develop/taichi/python/taichi/lang/kernel.py", line 459, in __call__
    return self.compiled_functions[key](*args)
  File "/home/bate/Develop/taichi/python/taichi/lang/kernel.py", line 423, in func__
    t_kernel()
RuntimeError: [verify.cpp:basic_verify@40] stmt 8 cannot have operand 7.
```

### PR DESCRIPTION
**Pull request by xumingkuan**
Related issue = fix #1297 

I moved the unreachable code elimination pass from `cfg_optimization` to `simplify` because the former can't eliminate container statements properly. I tried writing something like `std::vector<Stmt *> not_in_any_nodes` in the CFG, but it's hard to know whether a `ContinueStmt` can be eliminated in the CFG, so an `IfStmt` with only one `ContinueStmt` in it can't be eliminated easily too.

[[Click here for the format server]](http://kun.csail.mit.edu:31415/)

----

### CODE REVIEW

File: taichi/transforms/simplify.cpp [hunk 1]
```diff
@@ -1201,6 +1207,8 @@ bool simplify(IRNode *root, Kernel *kernel) {
     else
       break;
   }
+  if (modified)
+    fix_block_parents(root);
```
Comment (xumingkuan) [inline taichi/transforms/simplify.cpp:1211]: Corresponds to the sample 1 in the issue.

File: taichi/ir/ir.cpp [hunk 2]
```diff
@@ -665,7 +665,7 @@ void Block::insert(std::unique_ptr<Stmt> &&stmt, int location) {
 
 void Block::insert(VecStatement &&stmt, int location) {
   if (location == -1) {
-    location = (int)statements.size() - 1;
+    location = (int)statements.size();
```
Comment (xumingkuan) [inline taichi/ir/ir.cpp:668]: (I wonder why this has been in the codebase for 5 months...)

Comment (yuanming-hu) [reply taichi/ir/ir.cpp:668]: Thanks for fixing this! It's surprising that we have this issue for so long time without noticing...
