### PR TITLE
[Bug] [opengl] [llvm] [metal] Fix floordiv overflow when `lhs * rhs` is large

### LINKED ISSUE #969: [Bug] [opengl] [llvm] floordiv breaks when numbers are big
**Describe the bug**
`299999 // 100000`:
LLVM/x64: `1`
OpenGL: `3`
Python: `2`

**Log/Screenshots**
LLVM/x64:
```
[I 05/13/20 13:07:43.328] [compile_to_offloads.cpp:operator()@21] Simplified III:
kernel {
  $0 = offloaded  {
    <i32 x1> $1 = arg[0]
    <i32 x1> $2 = arg[1]
    <i32 x1> $3 = floordiv $1 $2
    <i32 x1> $4 : kernel return $3
  }
}
1
2
```
OpenGL before fix:
```[D 05/13/20 13:09:41.799] [opengl_api.cpp:display_kernel_info@318] source of kernel [func_c4_00] * 1:
#version 430 core
#extension GL_ARB_compute_shader: enable
#extension GL_ARB_gpu_shader_int64: enable
precision highp float;
layout(packed, binding = 6) buffer runtime { int _rand_state_; };
layout(packed, binding = 0) buffer data_i32 { int _data_i32_[]; };
layout(packed, binding = 0) buffer data_f32 { float _data_f32_[]; };
layout(packed, binding = 0) buffer data_f64 { double _data_f64_[]; };
layout(packed, binding = 0) buffer data_i64 { int64_t _data_i64_[]; };
layout(packed, binding = 1) buffer args_i32 { int _args_i32_[]; };
layout(packed, binding = 1) buffer args_f32 { float _args_f32_[]; };
layout(packed, binding = 1) buffer args_f64 { double _args_f64_[]; };
layout(packed, binding = 1) buffer args_i64 { int64_t _args_i64_[]; };

void func_c4_00()
{ // serial
  int B = _args_i32_[0 << 1];
  int C = _args_i32_[1 << 1];
  int D = int(B * C >= 0 ? abs(B) / abs(C) : sign(B) * (abs(B) + abs(C) - 1) / C);
  _args_i32_[0] = D;
}

void main()
{
  func_c4_00();
}
layout(local_size_x = 1 /* 1, 1 */, local_size_y = 1, local_size_z = 1) in;

3
2
```
OpenGL fixed:
```
[D 05/13/20 13:09:41.799] [opengl_api.cpp:display_kernel_info@318] source of kernel [func_c4_00] * 1:
#version 430 core
#extension GL_ARB_compute_shader: enable
#extension GL_ARB_gpu_shader_int64: enable
precision highp float;
layout(packed, binding = 6) buffer runtime { int _rand_state_; };
layout(packed, binding = 0) buffer data_i32 { int _data_i32_[]; };
layout(packed, binding = 0) buffer data_f32 { float _data_f32_[]; };
layout(packed, binding = 0) buffer data_f64 { double _data_f64_[]; };
layout(packed, binding = 0) buffer data_i64 { int64_t _data_i64_[]; };
layout(packed, binding = 1) buffer args_i32 { int _args_i32_[]; };
layout(packed, binding = 1) buffer args_f32 { float _args_f32_[]; };
layout(packed, binding = 1) buffer args_f64 { double _args_f64_[]; };
layout(packed, binding = 1) buffer args_i64 { int64_t _args_i64_[]; };

void func_c4_00()
{ // serial
  int B = _args_i32_[0 << 1];
  int C = _args_i32_[1 << 1];
  int D = int(B * C >= 0 || 1 == 1 ? abs(B) / abs(C) : sign(B) * (abs(B) + abs(C) - 1) / C);
  _args_i32_[0] = D;
}

void main()
{
  func_c4_00();
}
layout(local_size_x = 1 /* 1, 1 */, local_size_y = 1, local_size_z = 1) in;

2
2
```

**To Reproduce**
```py
import taichi as ti
import numpy as np
ti.init(arch=ti.x64, print_ir=True)
ti.set_logging_level(ti.DEBUG)
ti.core.toggle_advanced_optimization(False)

N = 300000
M = 100000
m = ti.var(ti.i32, ())

@ti.kernel
def func(i: ti.i32, j: ti.i32) -> ti.i32:
    return i // j

i = N - 1
actual = func(i, M)
expected = i // M
print(actual)
print(expected)
```

**If you have local commits (e.g. compile fixes before you reproduce the bug), please make sure you first make a PR to fix the build errors and then report the bug.**
Wait a minute..

### PR DESCRIPTION
**Pull request by archibate**
Related issue = closes #969

[[Click here for the format server]](http://kun.csail.mit.edu:31415/)

### CODE REVIEW

File: taichi/runtime/llvm/runtime.cpp [hunk 1]
```diff
@@ -88,7 +88,24 @@ void locked_task(void *lock, const T &func);
...
-  r -= T(a * b < 0 && b * r != a);
+  // simply `a * b < 0` may leads to overflow (#969)
+  //
+  // Formal Anti-Regression Verification (FARV):
+  //
+  // old = a * b < 0
+  // new = (a < 0) != (b < 0) && a
+  //
+  //  a  b old new
+  //  -  -  f = f (f&f)
```
Comment (k-ye) [inline taichi/runtime/llvm/runtime.cpp:99]: Nice comment! I think you forgot to update the rhs's value?

```suggestion
  //  -  -  f = f (f&t)
  //  -  +  t = t (t&t)
  //  0  -  f = f (t&f)
  //  0  +  f = f (f&f)
  //  +  -  t = t (t&t)
  //  +  +  f = f (f&t)
```

**Comment by archibate** [comment]
appveyor failed due to ad_reduce random crash. I thought rerunfailedtest already solve the problem?
