### PR TITLE
[llvm] Unify the llvm context of host and device

### LINKED ISSUE #7251: Unify the llvm context of host and device
**Describe the bug**
The `llvm_context_host_` and `llvm_context_device_` are never both used in the same backend, so we can unify them and only use a single `llvm_context_`.

### PR DESCRIPTION
**Pull request by lin-hitonami**
Issue: fixes #7251
The` llvm_context_host_` and `llvm_context_device_` are never both used in the same backend, so we can unify them and only use a single `llvm_context_`.

### CODE REVIEW

File: taichi/runtime/llvm/llvm_context.cpp [hunk 1]
```diff
@@ -95,6 +95,11 @@ TaichiLLVMContext::TaichiLLVMContext(CompileConfig *config, Arch arch)
     llvm::InitializeNativeTargetAsmParser();
 #endif
   } else if (arch == Arch::dx12) {
+    // FIXME: Must initialize these before initializing Arch::dx12
```
Comment (ailzhang) [inline taichi/runtime/llvm/llvm_context.cpp:98]: OOC: could you explain a bit why it wasn't required before this PR? :P Thanks!

**Review by ailzhang — COMMENTED** [review]
LGTM!

File: taichi/runtime/llvm/llvm_context.cpp (hunk 1 above)
Comment (lin-hitonami) [reply taichi/runtime/llvm/llvm_context.cpp:98]: Because we initialized the TaichiLLVMContext of CPU before initializing the context of the backend specified by config.arch regardless of what the backend is before. We don't initialized it now if the backend is not CPU.

**Comment by taichi-gardener** [comment]
Rebase failed, please resolve the conflicts manually.

**Review by ailzhang — APPROVED** [review]
Thanks!

File: taichi/runtime/llvm/llvm_context.cpp [hunk 2]
```diff
@@ -95,12 +95,19 @@ TaichiLLVMContext::TaichiLLVMContext(const CompileConfig &config, Arch arch)
...
+    llvm::InitializeNativeTargetAsmPrinter();
+    llvm::InitializeNativeTargetAsmParser();
+    /*
 #if defined(TI_WITH_DX12)
     LLVMInitializeDirectXTarget();
     LLVMInitializeDirectXTargetMC();
     LLVMInitializeDirectXTargetInfo();
     LLVMInitializeDirectXAsmPrinter();
 #endif
+    */
```
Comment (lin-hitonami) [inline taichi/runtime/llvm/llvm_context.cpp:110]:
```suggestion
#if defined(TI_WITH_DX12)
    LLVMInitializeDirectXTarget();
    LLVMInitializeDirectXTargetMC();
    LLVMInitializeDirectXTargetInfo();
    LLVMInitializeDirectXAsmPrinter();
#endif
```

File: taichi/runtime/llvm/llvm_context.cpp [hunk 3]
```diff
@@ -95,6 +95,11 @@ TaichiLLVMContext::TaichiLLVMContext(const CompileConfig &config, Arch arch)
     llvm::InitializeNativeTargetAsmParser();
 #endif
   } else if (arch == Arch::dx12) {
+    // FIXME: Must initialize these before initializing Arch::dx12
+    // because it uses the jit of CPU right now.
+    llvm::InitializeNativeTarget();
+    llvm::InitializeNativeTargetAsmPrinter();
+    llvm::InitializeNativeTargetAsmParser();
```
Comment (lin-hitonami) [inline taichi/runtime/llvm/llvm_context.cpp:102]:
```suggestion
    llvm::InitializeNativeTargetAsmParser();
    // The dx target is used elsewhere, so we need to initialize it too.
```
