### PR TITLE
[OpenGL] [refactor] Refactor OpenGL type system to support u32 and u64

### LINKED ISSUE #1931: [opengl] [test] "test_bit_operations::test_bit_shr" fails on opengl
**Describe the bug**
`ti.bit_shr` is demoted to `bit_sar` on opengl, but the data type becomes `u32`, which is not supported on opengl...

**To Reproduce**
`ti test bit_operations -v -t 1`.

```py
@ti.test()
def test_bit_shr():
    @ti.kernel
    def shr(a: ti.i32, b: ti.i32) -> ti.i32:
        return ti.bit_shr(a, b)

    n = 8
    test_num = 2**n
    neg_test_num = -test_num
    for i in range(n):
        assert shr(test_num, i) == 2**(n - i)
    for i in range(n):
        offset = 0x100000000 if i > 0 else 0
        assert shr(neg_test_num, i) == (neg_test_num + offset) >> i
```

**Log/Screenshots**
```
..\tests\python\test_bit_operations.py::test_bit_shr[opengl] [Taichi] Starting
 on arch=opengl
[Taichi] materializing...
[I 10/08/20 18:27:05.793] [compile_to_offloads.cpp:taichi::lang::irpass::`anon
ymous-namespace'::make_pass_printer::<lambda_fe1d620add3df83d4ee306f9c0ab10ca>
::operator ()@18] [shr_c14_0] Initial IR:
kernel {
  <i32 x1> $0 : kernel return (cast_value<int32> (arg[0] (dt=int32) shr arg[1]
 (dt=int32)))
}
[I 10/08/20 18:27:05.794] [compile_to_offloads.cpp:taichi::lang::irpass::`anon
ymous-namespace'::make_pass_printer::<lambda_fe1d620add3df83d4ee306f9c0ab10ca>
::operator ()@18] [shr_c14_0] Lowered:
kernel {
  <i32 x1> $0 = arg[0]
  <i32 x1> $1 = arg[1]
  $2 = bit_shr $0 $1
  $3 = cast_value<i32> $2
  <i32 x1> $4 : kernel return $3
}
[I 10/08/20 18:27:05.794] [compile_to_offloads.cpp:taichi::lang::irpass::`anon
ymous-namespace'::make_pass_printer::<lambda_fe1d620add3df83d4ee306f9c0ab10ca>
::operator ()@18] [shr_c14_0] Typechecked:
kernel {
  <i32 x1> $0 = arg[0]
  <i32 x1> $1 = arg[1]
  <i32 x1> $2 = bit_shr $0 $1
  <i32 x1> $3 = cast_value<i32> $2
  <i32 x1> $4 : kernel return $3
}
[I 10/08/20 18:27:05.795] [compile_to_offloads.cpp:taichi::lang::irpass::`anon
ymous-namespace'::make_pass_printer::<lambda_fe1d620add3df83d4ee306f9c0ab10ca>
::operator ()@18] [shr_c14_0] Simplified I:
kernel {
  <i32 x1> $0 = arg[0]
  <i32 x1> $1 = arg[1]
  <i32 x1> $2 = bit_shr $0 $1
  <i32 x1> $3 : kernel return $2
}
[I 10/08/20 18:27:05.796] [compile_to_offloads.cpp:taichi::lang::irpass::`anon
ymous-namespace'::make_pass_printer::<lambda_fe1d620add3df83d4ee306f9c0ab10ca>
::operator ()@18] [shr_c14_0] Access flagged I:
kernel {
  <i32 x1> $0 = arg[0]
  <i32 x1> $1 = arg[1]
  <i32 x1> $2 = bit_shr $0 $1
  <i32 x1> $3 : kernel return $2
}
[I 10/08/20 18:27:05.797] [compile_to_offloads.cpp:taichi::lang::irpass::`anon
ymous-namespace'::make_pass_printer::<lambda_fe1d620add3df83d4ee306f9c0ab10ca>
::operator ()@18] [shr_c14_0] Simplified II:
kernel {
  <i32 x1> $0 = arg[0]
  <i32 x1> $1 = arg[1]
  <i32 x1> $2 = bit_shr $0 $1
  <i32 x1> $3 : kernel return $2
}
[I 10/08/20 18:27:05.797] [compile_to_offloads.cpp:taichi::lang::irpass::`anon
ymous-namespace'::make_pass_printer::<lambda_fe1d620add3df83d4ee306f9c0ab10ca>
::operator ()@18] [shr_c14_0] Offloaded:
kernel {
  $0 = offloaded
  body {
    <i32 x1> $1 = arg[0]
    <i32 x1> $2 = arg[1]
    <i32 x1> $3 = bit_shr $1 $2
    <i32 x1> $4 : kernel return $3
  }
}
[I 10/08/20 18:27:05.798] [compile_to_offloads.cpp:taichi::lang::irpass::`anon
ymous-namespace'::make_pass_printer::<lambda_fe1d620add3df83d4ee306f9c0ab10ca>
::operator ()@18] [shr_c14_0] Optimized by CFG:
kernel {
  $0 = offloaded
  body {
    <i32 x1> $1 = arg[0]
    <i32 x1> $2 = arg[1]
    <i32 x1> $3 = bit_shr $1 $2
    <i32 x1> $4 : kernel return $3
  }
}
[I 10/08/20 18:27:05.798] [compile_to_offloads.cpp:taichi::lang::irpass::`anon
ymous-namespace'::make_pass_printer::<lambda_fe1d620add3df83d4ee306f9c0ab10ca>
::operator ()@18] [shr_c14_0] Access flagged II:
kernel {
  $0 = offloaded
  body {
    <i32 x1> $1 = arg[0]
    <i32 x1> $2 = arg[1]
    <i32 x1> $3 = bit_shr $1 $2
    <i32 x1> $4 : kernel return $3
  }
}
[I 10/08/20 18:27:05.799] [compile_to_offloads.cpp:taichi::lang::irpass::`anon
ymous-namespace'::make_pass_printer::<lambda_fe1d620add3df83d4ee306f9c0ab10ca>
::operator ()@18] [shr_c14_0] Simplified III:
kernel {
  $0 = offloaded
  body {
    <i32 x1> $1 = arg[0]
    <i32 x1> $2 = arg[1]
    <i32 x1> $3 = bit_shr $1 $2
    <i32 x1> $4 : kernel return $3
  }
}
[I 10/08/20 18:27:05.800] [compile_to_offloads.cpp:taichi::lang::irpass::`anon
ymous-namespace'::make_pass_printer::<lambda_fe1d620add3df83d4ee306f9c0ab10ca>
::operator ()@18] [shr_c14_0] Start offload_to_executable:
kernel {
  $0 = offloaded
  body {
    <i32 x1> $1 = arg[0]
    <i32 x1> $2 = arg[1]
    <i32 x1> $3 = bit_shr $1 $2
    <i32 x1> $4 : kernel return $3
  }
}
[I 10/08/20 18:27:05.800] [compile_to_offloads.cpp:taichi::lang::irpass::`anon
ymous-namespace'::make_pass_printer::<lambda_fe1d620add3df83d4ee306f9c0ab10ca>
::operator ()@18] [shr_c14_0] Dense struct-for demoted:
kernel {
  $0 = offloaded
  body {
    <i32 x1> $1 = arg[0]
    <i32 x1> $2 = arg[1]
    <i32 x1> $3 = bit_shr $1 $2
    <i32 x1> $4 : kernel return $3
  }
}
[I 10/08/20 18:27:05.801] [compile_to_offloads.cpp:taichi::lang::irpass::`anon
ymous-namespace'::make_pass_printer::<lambda_fe1d620add3df83d4ee306f9c0ab10ca>
::operator ()@18] [shr_c14_0] Make thread local:
kernel {
  $0 = offloaded
  body {
    <i32 x1> $1 = arg[0]
    <i32 x1> $2 = arg[1]
    <i32 x1> $3 = bit_shr $1 $2
    <i32 x1> $4 : kernel return $3
  }
}
[I 10/08/20 18:27:05.801] [compile_to_offloads.cpp:taichi::lang::irpass::`anon
ymous-namespace'::make_pass_printer::<lambda_fe1d620add3df83d4ee306f9c0ab10ca>
::operator ()@18] [shr_c14_0] Remove range assumption:
kernel {
  $0 = offloaded
  body {
    <i32 x1> $1 = arg[0]
    <i32 x1> $2 = arg[1]
    <i32 x1> $3 = bit_shr $1 $2
    <i32 x1> $4 : kernel return $3
  }
}
[I 10/08/20 18:27:05.802] [compile_to_offloads.cpp:taichi::lang::irpass::`anon
ymous-namespace'::make_pass_printer::<lambda_fe1d620add3df83d4ee306f9c0ab10ca>
::operator ()@18] [shr_c14_0] Access lowered:
kernel {
  $0 = offloaded
  body {
    <i32 x1> $1 = arg[0]
    <i32 x1> $2 = arg[1]
    <i32 x1> $3 = bit_shr $1 $2
    <i32 x1> $4 : kernel return $3
  }
}
[I 10/08/20 18:27:05.803] [compile_to_offloads.cpp:taichi::lang::irpass::`anon
ymous-namespace'::make_pass_printer::<lambda_fe1d620add3df83d4ee306f9c0ab10ca>
::operator ()@18] [shr_c14_0] DIE:
kernel {
  $0 = offloaded
  body {
    <i32 x1> $1 = arg[0]
    <i32 x1> $2 = arg[1]
    <i32 x1> $3 = bit_shr $1 $2
    <i32 x1> $4 : kernel return $3
  }
}
[I 10/08/20 18:27:05.804] [compile_to_offloads.cpp:taichi::lang::irpass::`anon
ymous-namespace'::make_pass_printer::<lambda_fe1d620add3df83d4ee306f9c0ab10ca>
::operator ()@18] [shr_c14_0] Access flagged III:
kernel {
  $0 = offloaded
  body {
    <i32 x1> $1 = arg[0]
    <i32 x1> $2 = arg[1]
    <i32 x1> $3 = bit_shr $1 $2
    <i32 x1> $4 : kernel return $3
  }
}
[I 10/08/20 18:27:05.804] [compile_to_offloads.cpp:taichi::lang::irpass::`anon
ymous-namespace'::make_pass_printer::<lambda_fe1d620add3df83d4ee306f9c0ab10ca>
::operator ()@18] [shr_c14_0] Atomics demoted:
kernel {
  $0 = offloaded
  body {
    <i32 x1> $1 = arg[0]
    <i32 x1> $2 = arg[1]
    <i32 x1> $3 = bit_shr $1 $2
    <i32 x1> $4 : kernel return $3
  }
}
[I 10/08/20 18:27:05.805] [compile_to_offloads.cpp:taichi::lang::irpass::`anon
ymous-namespace'::make_pass_printer::<lambda_fe1d620add3df83d4ee306f9c0ab10ca>
::operator ()@18] [shr_c14_0] Operations demoted:
kernel {
  $0 = offloaded
  body {
    <i32 x1> $1 = arg[0]
    <i32 x1> $2 = arg[1]
    <u32 x1> $3 = reinterpret_cast_bits<u32> $1
    <u32 x1> $4 = cast_value<u32> $2
    <u32 x1> $5 = bit_sar $3 $4
    <i32 x1> $6 = reinterpret_cast_bits<i32> $5
    <i32 x1> $7 : kernel return $6
  }
}
[I 10/08/20 18:27:05.806] [compile_to_offloads.cpp:taichi::lang::irpass::`anon
ymous-namespace'::make_pass_printer::<lambda_fe1d620add3df83d4ee306f9c0ab10ca>
::operator ()@18] [shr_c14_0] Simplified IV:
kernel {
  $0 = offloaded
  body {
    <i32 x1> $1 = arg[0]
    <i32 x1> $2 = arg[1]
    <u32 x1> $3 = reinterpret_cast_bits<u32> $1
    <u32 x1> $4 = cast_value<u32> $2
    <u32 x1> $5 = bit_sar $3 $4
    <i32 x1> $6 = reinterpret_cast_bits<i32> $5
    <i32 x1> $7 : kernel return $6
  }
}
[E 10/08/20 18:27:05.807] [taichi/backends/opengl/opengl_data_types.h:taichi::
lang::opengl::opengl_data_type_name@20] Not supported.

```

### PR DESCRIPTION
**Pull request by archibate**
Related issue = close #1931

[[Click here for the format server]](http://kun.csail.mit.edu:31415/)

----
test_bit_operations now passing on opengl, we can merge #2014 right after this is merged.

### CODE REVIEW

File: taichi/backends/opengl/codegen_opengl.cpp [hunk 1]
```diff
@@ -467,17 +480,51 @@ class KernelGen : public IRVisitor {
...
+      auto src_type = stmt->operand->element_type();
+
+      if ((dst_type->is_primitive(PrimitiveTypeID::u32) &&
+           src_type->is_primitive(PrimitiveTypeID::i32)) ||
+          (dst_type->is_primitive(PrimitiveTypeID::u64) &&
+           src_type->is_primitive(PrimitiveTypeID::i64)) ||
+          (dst_type->is_primitive(PrimitiveTypeID::i32) &&
+           src_type->is_primitive(PrimitiveTypeID::u32)) ||
+          (dst_type->is_primitive(PrimitiveTypeID::i64) &&
+           src_type->is_primitive(PrimitiveTypeID::u64))) {
```
Comment (yuanming-hu) [inline taichi/backends/opengl/codegen_opengl.cpp:493]: We can probably leverage `is_integral` and `data_type_size` here to avoid repeated comparisons.

File: taichi/backends/opengl/codegen_opengl.cpp [hunk 2]
```diff
@@ -467,17 +480,51 @@ class KernelGen : public IRVisitor {
...
+                  src_type->is_primitive(PrimitiveTypeID::u64))) {
+        emit("{} {} = uintBitsToFloat({});", dt_name, stmt->short_name(),
+             stmt->operand->short_name());
+
+      } else if ((dst_type->is_primitive(PrimitiveTypeID::u32) &&
+                  src_type->is_primitive(PrimitiveTypeID::f32)) ||
+                 (dst_type->is_primitive(PrimitiveTypeID::u64) &&
+                  src_type->is_primitive(PrimitiveTypeID::f64))) {
+        emit("{} {} = floatBitsToUint({});", dt_name, stmt->short_name(),
+             stmt->operand->short_name());
```
Comment (yuanming-hu) [inline taichi/backends/opengl/codegen_opengl.cpp:523]: The repeated if-condition enumerations here might not be the best way to implement a pattern like this. Given the emitted instructions all follow an "XBitsToY" structure, maybe we can simplify the code here a little bit?

File: taichi/backends/opengl/codegen_opengl.cpp [hunk 3]
```diff
@@ -136,42 +142,39 @@ class KernelGen : public IRVisitor {
...
+                    + ") buffer " #name "_u32 { uint _" #name "_u32_[]; };\n"; \
+    if (used.uint64) \
+      kernel_header += "layout(std430, binding = " + fmt::format("{}", id) \
+                    + ") buffer " #name "_u64 { uint64_t _" #name "_u64_[]; };\n"; \
+    if (used.float32) \
+      kernel_header += "layout(std430, binding = " + fmt::format("{}", id) \
+                    + ") buffer " #name "_f32 { float _" #name "_f32_[]; };\n"; \
+    if (used.float64) \
+      kernel_header += "layout(std430, binding = " + fmt::format("{}", id) \
+                    + ") buffer " #name "_f64 { double _" #name "_f64_[]; };\n"; \
```
Comment (yuanming-hu) [inline taichi/backends/opengl/codegen_opengl.cpp:164]: Maybe use a macro to avoid repetition?

**Review by yuanming-hu — COMMENTED** [review]
Awesome! This mostly LGTM. My only concern is a few places use repeated code, which doesn't follow well the DRY principle and cause troubles for maintenance. Could you refactor there a bit?

File: taichi/backends/opengl/codegen_opengl.cpp [hunk 4]
```diff
@@ -467,17 +473,42 @@ class KernelGen : public IRVisitor {
...
-      if (stmt->cast_type->is_primitive(PrimitiveTypeID::f32) &&
-          stmt->operand->element_type()->is_primitive(PrimitiveTypeID::i32)) {
+      auto dst_type = stmt->cast_type;
+      auto src_type = stmt->operand->element_type();
+      auto dst_int = 0;
+      if (is_integral(dst_type))
+        dst_int = is_unsigned(dst_type) ? 2 : 1;
+      auto src_int = 0;
+      if (is_integral(src_type))
+        src_int = is_unsigned(src_type) ? 2 : 1;
```
Comment (yuanming-hu) [inline taichi/backends/opengl/codegen_opengl.cpp:483]: Instead of using magic numbers `0, 1, 2`, maybe use a few local `constexpr` constant identifiers for readability? E.g. `constexpr int signed_integer_type = 0;`.

Variable names `dst_int` and `src_int` are a bit misleading since they can represent float-point types as well.

**Review by yuanming-hu — COMMENTED** [review]
Thanks for the updates! Looks better now.

**Review by yuanming-hu — APPROVED** [review]
LGTM. Thanks!

**Comment by ffcr** [comment]
In addition, when arch is OpenGL, it will crash and display "Type u8 not supported."
