### PR TITLE
[Opt] [Refactor] [Bug] Use state machines for optimization on variables

### LINKED ISSUE #882: [Bug] [Opt] `continue` in `if` doesn't work with advanced optimization
**Describe the bug**
<del>I was testing my store-forwarding code but found a test that is failing even if `advanced_optimization = false`.</del>
It passes with `advanced_optimization = false`, and fails with `advanced_optimization = true`.

**Log/Screenshots**
```
>       assert val[None] == 1515
E       assert 1610 == 1515
```

**To Reproduce**
```python
@ti.all_archs
def test_advanced_store_forwarding_continue_in_if():
    ti.init(print_ir=True)
    val = ti.var(ti.i32)
    ti.root.place(val)

    @ti.kernel
    def func(n: ti.i32):
        # Launch just one thread
        for _ in range(1):
            a = 10
            b = 0
            for i in range(n):
                b += a
                a = i
                if i == 5:
                    continue
                a = 100
            a = 1000
            val[None] = a + b

    func(1)
    assert val[None] == 1010
    func(5)
    assert val[None] == 1410
    func(6)
    assert val[None] == 1510
    func(7)
    assert val[None] == 1515
```

### PR DESCRIPTION
**Pull request by xumingkuan**
Related issue = #656
Related PR = https://github.com/taichi-dev/taichi/pull/858#issuecomment-618752501

Fix #882 (related PR = #662)
Fix crash when `print_benchmark_stat=True` and there is `/` in `PYTEST_CURRENT_TEST`

Benchmark: **total running time** of 347 tests at commit https://github.com/taichi-dev/taichi/pull/859/commits/d225b63f61d23fc391211771acc8ae6163ee226e.
**before**: (rerun 3 times) 224.65s 225.20s 220.76s (average: 223.54s)
**after**: 218.94s 214.22s 210.33s (average: 214.50s)

After the commit https://github.com/taichi-dev/taichi/pull/859/commits/10ee8454ac3f5940e44717adcfcce9c4ecdcbb06: 213.52s
`master` branch with commit https://github.com/taichi-dev/taichi/pull/859/commits/10ee8454ac3f5940e44717adcfcce9c4ecdcbb06 cherry-picked: 214.64s

Optimization factor is slightly decreased, due to more cautious treatment on loops:
**before**:
benchmark20200426_4
**after**:
benchmark20200426_3

[[Click here for the format server]](http://kun.csail.mit.edu:31415/)

### CODE REVIEW

**Comment by xumingkuan** [comment]
I need to know if an `AtomicOpStmt` is used in other places quickly (say O(1)) to achieve an O(n * (number of statements to be eliminated)) running time in total in the whole pass. (The `optimize_local_variable` pass is now O(n * (number of statements to be eliminated) * (number of `AllocaStmt`s)))

Is there a better way than passing `std::unordered_set<AtomicOpStmt *> *used_atomics;` to the constructor?

**Comment by xumingkuan** [comment]
What about making it a static variable, and provide a function to rebuild the set?

**Comment by yuanming-hu** [comment]
I'm not sure if I fully understand the context of your question, but I believe you can make your own decision :-)

**Comment by xumingkuan** [comment]
My brain is fried... I found `gather_loads_and_stores_in_blocks` is not convenient to use:
For each loop (O(1)?), for each load/store statement (O(n)), **for each variable that may be modified by that statement** (O(n)), do something like `maybe_store()`. 

This is causing at least O(n^3) time in this pass, and finding variables that may be modified by a statement is non-trivial and can be an overkill.

I use the pattern of simply visiting twice for now. Maybe we want to split `GlobalPtrStmt` out, because we can do aliasing analysis for the other two types of variables easily.

**Comment by xumingkuan** [comment]
```
kernel {
  <i32 x1> $0 = arg[0]
  <i32*x1> $1 = global ptr [S2place_i32], index [] activate=true
  <gen*x1> $4 = get root
  <i32 x1> $5 = linearized(ind {}, stride {})
  <gen*x1> $6 = [S0root][root]::lookup($4, $5) activate = false
  <gen*x1> $7 = get child [S0root->S1dense] $6
  <i32 x1> $8 = linearized(ind {}, stride {})
  <gen*x1> $9 = [S1dense][dense]::lookup($7, $8) activate = false
  <i32*x1> $10 = get child [S1dense->S2place_i32] $9
  <i32 x1> $11 = shuffle $10[0]
  <i32 x1> $2 : global store [$11 <- $0]
}
```
So `ArgLoadStmt` can also be a variable?

**Comment by xumingkuan** [comment]
Currently `VariableOptimize` only supports optimization on local variables. I'll add support of global temps/pointers in the next PR.

**Comment by xumingkuan** [comment]
`LoadsAndStoresSearcher` is actually unused...

File: taichi/ir/state_machine.h [hunk 1]
```diff
@@ -0,0 +1,82 @@
...
+    definitely
+  };
+  State stored;  // Is this variable ever stored (or atomic-operated)?
+  State stored_in_this_if_or_loop;
+  State loaded;  // Is this variable ever loaded (or atomic-operated)?
+  State loaded_in_this_if_or_loop;
+
+  static State merge(const State &a, const State &b) {
+    if (a == definitely || b == definitely)
+      return definitely;
```
Comment (yuanming-hu) [inline taichi/ir/state_machine.h:31]: Should this be `a == definitely && b == definitely`?

File: taichi/analysis/gather_loads_and_stores_in_blocks.cpp [hunk 2]
```diff
@@ -0,0 +1,56 @@
+#include "taichi/ir/ir.h"
+#include <unordered_set>
+
+TLANG_NAMESPACE_BEGIN
+
+// Gather all loads, stores and atomic operations for each block.
+class LoadsAndStoresSearcher : public BasicStmtVisitor {
```
Comment (yuanming-hu) [inline taichi/analysis/gather_loads_and_stores_in_blocks.cpp:7]: If this is not uesd, we should save it for a future PR.

File: taichi/analysis/gather_used_atomics.cpp [hunk 3]
```diff
@@ -5,20 +5,21 @@ TLANG_NAMESPACE_BEGIN
 
 class UsedAtomicsSearcher : public BasicStmtVisitor {
  private:
-  std::unordered_set<AtomicOpStmt *> used_atomics;
+  std::unique_ptr<std::unordered_set<AtomicOpStmt *>> used_atomics;
```
Comment (yuanming-hu) [inline taichi/analysis/gather_used_atomics.cpp:8]: If the goal is to avoid copying, `std::unordered_set` itself is movable and we don't need `std::unique_ptr`.

File: taichi/ir/state_machine.cpp [hunk 4]
```diff
@@ -0,0 +1,331 @@
+#include "state_machine.h"
+
+TLANG_NAMESPACE_BEGIN
+
+std::unique_ptr<std::unordered_set<AtomicOpStmt *>> StateMachine::used_atomics;
```
Comment (yuanming-hu) [inline taichi/ir/state_machine.cpp:5]: Shall we make it a member instead of a global var? (If this is too troublesome we should leave this refactoring to a future PR.)

Comment (xumingkuan) [reply taichi/ir/state_machine.cpp:5]: This is the default initialization of the static member variable... Is this statement unnecessary?

Comment (yuanming-hu) [reply taichi/ir/state_machine.cpp:5]: You are right - I missed `StateMachine::`. Sorry about that.

File: taichi/analysis/gather_used_atomics.cpp (hunk 3 above)
Comment (xumingkuan) [reply taichi/analysis/gather_used_atomics.cpp:8]: Oh I didn't know it. Will `return searcher.used_atomics;` avoid copying in `static std::unordered_set<AtomicOpStmt *> run(IRNode *root)` (where `searcher` is a temporary variable)?

Comment (yuanming-hu) [reply taichi/analysis/gather_used_atomics.cpp:8]: That depends on a few features of C++: copy elision and return value optimization. You might also need `return std::move(...);`, which might or might not be helpful if you have copy elision and RVO...

File: taichi/ir/state_machine.h (hunk 1 above)
Comment (xumingkuan) [reply taichi/ir/state_machine.h:31]: You're right. `stored = merge(true_branch.stored, false_branch.stored);` and `merge(true_branch.stored_in_this_if_or_loop, false_branch.stored_in_this_if_or_loop)` should be `a == definitely && b == definitely`, but `stored_in_this_if_or_loop = merge(stored_in_this_if_or_loop, merge_result` should be `a == definitely || b == definitely`...

Comment (yuanming-hu) [reply taichi/ir/state_machine.h:31]: I feel like `stored_in_this_if_or_loop` should not be a `State`, but two `State`s. This might help clarify the logic here...

File: taichi/ir/state_machine.cpp (hunk 4 above)
Comment (yuanming-hu) [reply taichi/ir/state_machine.cpp:5]: Wait, I feel like the ownership of this static variable is still unclear. To me, it seems that `StateMachine` should not own this. Its owner should be `VariableOptimization`.

File: taichi/analysis/gather_loads_and_stores_in_blocks.cpp (hunk 2 above)
Comment (xumingkuan) [reply taichi/analysis/gather_loads_and_stores_in_blocks.cpp:7]: I think this will never be used in the current code framework. Shall we just delete this file (if you like my design of `bool VariableOptimize::maybe_run;`)?

File: taichi/ir/state_machine.h (hunk 1 above)
Comment (xumingkuan) [reply taichi/ir/state_machine.h:31]: I named it like this because we can't eliminate `a = 1;` in these cases:
```C++
a = 1;
if (...)
  a = 2;
```
```C++
a = 1;
for (...)
  a = 2;
```
But we *can* eliminate `a = 1` in this case:
```C++
a = 1;
{
  a = 2;
}
```

Comment (xumingkuan) [reply taichi/ir/state_machine.h:31]: It's just `if` and `for` are "maybe" executed.

Comment (yuanming-hu) [reply taichi/ir/state_machine.h:31]: I see. Do you have a moment to briefly chat about these on zoom?

Comment (xumingkuan) [reply taichi/ir/state_machine.h]: Sure. (I've just pushed a commit about these)

File: taichi/analysis/gather_used_atomics.cpp (hunk 3 above)
Comment (xumingkuan) [reply taichi/analysis/gather_used_atomics.cpp:8]: I just realized that I used `std::unique_ptr` to distinguish the uninitialized case (which should not happen) and an empty set.

File: taichi/transforms/variable_optimization.cpp [hunk 5]
```diff
@@ -0,0 +1,204 @@
+#include "taichi/ir/ir.h"
+#include "taichi/ir/state_machine.h"
+#include <unordered_map>
+
+TLANG_NAMESPACE_BEGIN
+
+class VariableOptimize : public IRVisitor {
+ private:
+  std::unique_ptr<std::unordered_map<Stmt *, StateMachine>> state_machines;
```
Comment (xumingkuan) [inline taichi/transforms/variable_optimization.cpp:9]: I'll do a refactor on this in the next PR.

File: taichi/ir/state_machine.cpp (hunk 4 above)
Comment (xumingkuan) [reply taichi/ir/state_machine.cpp:5]: It's more convenient to write it in `StateMachine` now, because I do all modification on IR in `StateMachine`......

**Comment by xumingkuan** [comment]
Shall I rename state_machine.cpp?
