### PR TITLE
[lang] [bug] Fix setting integer arguments within u64 range but greater than i64 range

### LINKED ISSUE #6264: Can't pass in numbers >= 2^63 as ti.u64
**Describe the bug**
Can't pass in numbers >= 2^63 as ti.u64

**To Reproduce**

```py
import taichi as ti
ti.init()

@ti.kernel
def foo(a: ti.u64):
    pass

foo(2 ** 63)
```

**Log/Screenshots**
```
[Taichi] version 1.1.4, llvm 10.0.0, commit 38c0277f, linux, python 3.9.12
[Taichi] Starting on arch=x64
Traceback (most recent call last):
  File "/home/lin/test/overflow.py", line 8, in <module>
    foo(2 ** 63)
  File "/home/lin/taichi/python/taichi/lang/kernel_impl.py", line 915, in wrapped
    return primal(*args, **kwargs)
  File "/home/lin/taichi/python/taichi/lang/kernel_impl.py", line 842, in __call__
    return self.runtime.compiled_functions[key](*args)
  File "/home/lin/taichi/python/taichi/lang/kernel_impl.py", line 649, in func__
    launch_ctx.set_arg_int(actual_argument_slot, int(v))
TypeError: set_arg_int(): incompatible function arguments. The following argument types are supported:
    1. (self: taichi._lib.core.taichi_python.KernelLaunchContext, arg0: int, arg1: int) -> None

Invoked with: <taichi._lib.core.taichi_python.KernelLaunchContext object at 0x7f49f04438b0>, 0, 9223372036854775808

```

### PR DESCRIPTION
**Pull request by lin-hitonami**
Issue: fixes #6264

### CODE REVIEW

**Review by jim19930609 — APPROVED** [review]

File: taichi/program/kernel.cpp [hunk 1]
```diff
@@ -185,15 +185,15 @@ void Kernel::LaunchContextBuilder::set_arg_float(int arg_id, float64 d) {
...
 }
 
-void Kernel::LaunchContextBuilder::set_arg_int(int arg_id, int64 d) {
+void Kernel::LaunchContextBuilder::set_arg_int(int arg_id, uint64 d) {
   TI_ASSERT_INFO(!kernel_->args[arg_id].is_array,
                  "Assigning scalar value to external (numpy) array argument is "
                  "not allowed.");
 
   ActionRecorder::get_instance().record(
       "set_kernel_arg_int64",
```
Comment (jim19930609) [inline taichi/program/kernel.cpp:194]: Shall we simply record "set_kernel_arg_integer" rather than "int64" (which isn't the case)?

**Review by jim19930609 — APPROVED** [review]
