### PR TITLE
[bug] Cast scalar to right type before converting to uint64

### LINKED ISSUE #5169: [AOT] Assign correct precision type for float args
PR #5165 supports Matrix and Vectors for graph arguments. However, I have encountered problems when using data tuples with different precision.

In current graph implementation, the float args are always force cast to `double` or `float` type (after the PR is merged). It causes unexpected casting behavior when writing data into args buffer, like casting a `ti.f32` to `double` or vice versa.

The graph args should be assigned correct type from the Python side objects. 

A minimal example to reproduce some value errors:
```Python
import taichi as ti

ti.init(arch=ti.vulkan, print_ir=False)

N = 5

def test(dt):
    @ti.kernel
    def foo(a: ti.types.vector(N, dt), res: ti.types.ndarray(field_dim=1)):
        res[0] = a.sum()

    res_arr = ti.ndarray(dt, shape=(1,))
    B = ti.Vector([4.965] * N, dt)


    sym_A = ti.graph.Arg(ti.graph.ArgKind.SCALAR, 'mat', dt)
    sym_res = ti.graph.Arg(ti.graph.ArgKind.NDARRAY, 'res', dt)
    builder = ti.graph.GraphBuilder()
    builder.dispatch(foo, sym_A, sym_res)
    graph = builder.compile()
    graph.run({"mat" : B, "res" : res_arr})
    print(res_arr.to_numpy())

test(ti.f32)
test(ti.f64)
``` 
Output:
```
[Taichi] version 1.0.3, llvm 10.0.0, commit 1c02c987, linux, python 3.9.7
Failed to establish dbus connection[Taichi] Starting on arch=vulkan
Failed to establish dbus connection[I 06/14/22 21:49:02.388 127251] [vulkan_device_creator.cpp:pick_physical_device@364] Found Vulkan Device 0 (NVIDIA GeForce RTX 3080)
[I 06/14/22 21:49:02.388 127251] [vulkan_device_creator.cpp:pick_physical_device@364] Found Vulkan Device 1 (llvmpipe (LLVM 12.0.0, 256 bits))
[I 06/14/22 21:49:02.388 127251] [vulkan_device_creator.cpp:find_queue_families@141] Async compute queue 2, graphics queue 0
[I 06/14/22 21:49:02.388 127251] [vulkan_device_creator.cpp:find_queue_families@141] Async compute queue 2, graphics queue 0
[I 06/14/22 21:49:02.388 127251] [vulkan_device_creator.cpp:create_logical_device@427] Vulkan Device "NVIDIA GeForce RTX 3080" supports Vulkan 0 version 1.2.186
[24.825]
[3.4675801e-309]
```
The output for `ti.f64` is unexpected.

The downcast occurs in [here](https://github.com/taichi-dev/taichi/blob/633c628b5f40f53438863329ed80b8f19ace4a47/taichi/python/export_lang.cpp#L613-L619), we should make clear assignations for at least i32, i64, f32, f64.

### PR DESCRIPTION
**Pull request by ailzhang**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #5363
* #5362
* #5361
* #5360

Fixes #5169

### CODE REVIEW

File: taichi/aot/graph_data.h [hunk 1]
```diff
@@ -95,6 +95,7 @@ struct TI_DLL_EXPORT IValue {
   template <typename T,
             typename = std::enable_if_t<!std::is_same<T, Ndarray>::value, void>>
   static IValue create(T v) {
+    std::cout << v << std::endl;
```
Comment (turbo0628) [inline taichi/aot/graph_data.h:98]: Is this an intended print?

Comment (ailzhang) [reply taichi/aot/graph_data.h:98]: ah nice catch!

**Review by turbo0628 — APPROVED** [review]
Thanks, LGTM!
