### PR TITLE
[bug] Fixed type promotion rule for bit-shift operations

### LINKED ISSUE #4795: Shifting operators should not adopt the same implicit conversion rule as other arithmetic operators
Shifting operators like `<<` should take the left-side type as its result type (`i8 << u32 = i8`) instead of following rules for other arithmetic operators (`i8 + u32 = u32`).

### PR DESCRIPTION
**Pull request by jim19930609**
Related issue = fix #4795

bit-shift ops should not follow the same type promotion rule as numerical, for example:
- ops numerical ops: `u8 + i32 = i32`
- shift_ops:                `u8 << i32 = u8` (follow lhs's dtype)

As truncating rhs(i32) to u8 risks an overflow (very unlikely though), we inserted an AssertStmt to warn user of this potential overflow if initialized with debug=True.

Before:
image

After this patch (with debug=True): 
image

### CODE REVIEW

File: taichi/transforms/type_check.cpp [hunk 1]
```diff
@@ -5,6 +5,7 @@
 #include "taichi/ir/transforms.h"
 #include "taichi/ir/analysis.h"
 #include "taichi/ir/frontend_ir.h"
+#include <iostream>
```
Comment (ailzhang) [inline taichi/transforms/type_check.cpp:8]: is it still necessary? ;)

File: tests/python/test_type_promotion.py [hunk 2]
```diff
@@ -60,3 +60,17 @@ def func():
...
+    @ti.kernel
+    def test():
+        rhs = ti.cast(1, ti.i32)
+        lhs = ti.cast(16, ti.u8)
+
+        res = lhs << rhs
+        ti.static_assert(res.ptr.get_ret_type().to_string() == 'u8',
+                         "Incorrect type promotion for shift operations.")
+
+    test()
```
Comment (ailzhang) [inline tests/python/test_type_promotion.py:76]: FYI you can find some examples of testing assertion in `tests/python/test_debug.py` ;)

**Review by ailzhang — APPROVED** [review]
LGTM!

File: taichi/transforms/type_check.cpp (hunk 1 above)
Comment (jim19930609) [reply taichi/transforms/type_check.cpp:8]: Opps, forgot to remove this

File: tests/python/test_type_promotion.py (hunk 2 above)
Comment (jim19930609) [reply tests/python/test_type_promotion.py:76]: great, thanks!

File: tests/python/test_type_promotion.py [hunk 3]
```diff
@@ -60,3 +60,17 @@ def func():
     func()
 
     assert np.allclose(y.to_numpy(), np.sqrt(x.to_numpy()))
+
+
+@test_utils.test()
+def test_shift_ops():
```
Comment (strongoier) [inline tests/python/test_type_promotion.py:66]: I suggest writing cpp tests for type check. FYI https://github.com/taichi-dev/taichi/blob/master/tests/cpp/ir/frontend_type_inference_test.cpp

Comment (jim19930609) [reply tests/python/test_type_promotion.py:66]: sounds good. Let me see if I can write a similar one at CHI IR level.

File: taichi/transforms/type_check.cpp [hunk 4]
```diff
@@ -244,6 +244,43 @@ class TypeCheck : public IRVisitor {
     return stmt;
   }
 
+  void insert_shift_op_assertion_before(Stmt *stmt, Stmt *lhs, Stmt *rhs) {
+    int rhs_limit = 64;
```
Comment (strongoier) [inline taichi/transforms/type_check.cpp:248]: A few comments.
1. `lhs` and `rhs` cannot be floats.
2. There's a `data_type_bits()` function.
3. In Taichi, runtime assertions are only inserted when `ti.init(debug=True)` for performance considerations.

File: taichi/transforms/type_check.cpp [hunk 5]
```diff
@@ -287,7 +324,26 @@ class TypeCheck : public IRVisitor {
       };
       stmt->lhs = promote_custom_int_type(stmt, stmt->lhs);
       stmt->rhs = promote_custom_int_type(stmt, stmt->rhs);
-      auto ret_type = promoted_type(stmt->lhs->ret_type, stmt->rhs->ret_type);
+
+      DataType ret_type;
+      if (is_shift_op(stmt->op_type)) {
+        // shift_ops does not follow the same type promotion rule as numerical
```
Comment (strongoier) [inline taichi/transforms/type_check.cpp:330]: As shift op is special, why do we still cast rhs to the same type as lhs?

File: taichi/transforms/type_check.cpp (hunk 4 above)
Comment (jim19930609) [reply taichi/transforms/type_check.cpp:248]: Great suggestions, Thanks!

File: taichi/transforms/type_check.cpp (hunk 5 above)
Comment (jim19930609) [reply taichi/transforms/type_check.cpp:330]: Personally I'd prefer making explicit operations at CHI IR level or above, otherwise we have to rely on each specific backend to perform this implicit type cast - their type casting rule may not be consistent with each other.

Btw LLVM doesn't even bother performing this casting:
image

Comment (strongoier) [reply taichi/transforms/type_check.cpp:330]: Thanks for trying this :-) Then let's keep this behavior.

File: tests/python/test_type_promotion.py (hunk 3 above)
Comment (jim19930609) [reply tests/python/test_type_promotion.py]: Switched to Cpp test case. Thanks!

File: taichi/transforms/type_check.cpp (hunk 4 above)
Comment (jim19930609) [reply taichi/transforms/type_check.cpp]: Done.

**Review by strongoier — APPROVED** [review]
LGTM!
