### PR TITLE
[IR] Fix illegal intermediate IRs

### LINKED ISSUE #739: [ir] Fix illegal intermediate IRs
The new `verify` pass (#731) finds some IRs illegal in the process of `compile_to_offloads()`.

We may want to make each IR legal after `typecheck()`, so that we can uncomment https://github.com/taichi-dev/taichi/pull/731#discussion_r406554459 and find potential bugs in IR transform passes as early as possible.

Or, less probably, some IRs cannot become "legal" in the sense of current `verify` pass. If this happens, let's discuss what to do then.

List of tests to fix:
- [x] test_ad_if
- [x] test_atomic
- [x] test_grouped
- [x] test_local_atomics
- [x] test_loops
- [x] test_offload_cross
- [x] test_sparse_deactivate
- [x] test_sparse_parallel

### PR DESCRIPTION
**Pull request by xumingkuan**
Fix #739.

All hotfixes are removed.

[[Click here for the format server]](http://kun.csail.mit.edu:31415/)

### CODE REVIEW

File: taichi/transforms/offload.cpp [hunk 1]
```diff
@@ -489,9 +489,8 @@ void insert_gc(IRNode *root) {
     auto snodes = gc_statements[i].second;
     for (auto *snode : snodes) {
       if (is_gc_able(snode->type)) {
-        b->statements.insert(
-            b->statements.begin() + i + 1,
-            Stmt::make<OffloadedStmt>(OffloadedStmt::TaskType::gc, snode));
+        b->insert(Stmt::make<OffloadedStmt>(OffloadedStmt::TaskType::gc, snode),
+                  i + 1);
```
Comment (xumingkuan) [inline taichi/transforms/offload.cpp:493]: Modifying `Block::statements` directly without setting `parent` was really bad...

If we set `Block::statements` to be `private` to prevent code fragments like this, we may need some functions like `Block::get_statements()` to keep code fragments like `for (auto &stmt : b->statements)` neat?

Comment (yuanming-hu) [reply taichi/transforms/offload.cpp:493]: Right, probably something like `Block::get_statements() const`.
