### PR TITLE
[bug] Improve error message with GlobalPtrStmt indexing

### LINKED ISSUE #5467: Add descriptive names to fields
When debugging the out of index error for fields, we don't have a descriptive name for the field:

```python
import taichi as ti
ti.init(debug=True)

x = ti.field(int, shape=(2, 2))

@ti.kernel
def test():
    x[3, 3] = 1

test()
```

The above code gives error
```
taichi.lang.exception.TaichiAssertionError: 
(kernel=test_c56_0) Accessing field (S2place<i32>) of size (2, 2) with indices (3, 3)
```

The name `test_c56_0` is quite obscure here, shall we use a more descriptive name for it?

### PR DESCRIPTION
**Pull request by jim19930609**
Related issue = #5563, fix #5467 

Rearranging "debug info" will become part of CHI IR refactor. Some notes were updated in #5563

### CODE REVIEW

File: taichi/transforms/lower_ast.cpp [hunk 1]
```diff
@@ -391,7 +391,9 @@ class LowerAST : public IRVisitor {
           expr->stmt);
     } else if (dest.is<IndexExpression>()) {
       auto ix = dest.cast<IndexExpression>();
+
```
Comment (strongoier) [inline taichi/transforms/lower_ast.cpp:394]: Are these empty lines added by intention?

**Review by strongoier — APPROVED** [review]
Thanks!

File: taichi/transforms/lower_ast.cpp (hunk 1 above)
Comment (jim19930609) [reply taichi/transforms/lower_ast.cpp:394]: This is weird. Let me remove this
