### PR TITLE
[Opt] Fix redundant clone of stmts across offloaded tasks

### LINKED ISSUE #7923: [bug] Inconsistent results on Vulkan backend
**Describe the bug**
Vulkan backend produces incorrect value for `ti.Vector.field`.

**To Reproduce**

```python
import taichi as ti                                                                                                               
                                                                                                                                  
ti.init(arch=ti.vulkan)                                                                                                           
# ti.init(arch=ti.cpu)                                                                                                            
a = ti.Vector.field(2,dtype=ti.f32,shape=1)                                                                                       
b = ti.Vector.field(2,dtype=ti.f32,shape=1)                                                                                       
c = ti.Vector.field(2,dtype=ti.f32,shape=1)                                                                                       
                                                                                                                                  
@ti.kernel                                                                                                                        
def test():                                                                                                                       
    a[0] = ti.Vector([1, 1])                                                                                                      
    b[0] = ti.Vector([0, 0])                                                                                                      
    c[0] = ti.Vector([0, 0])                                                                                                      
    b[0] += a[0]  # b[0] = [1, 1]                                                                                                 
    b[0] /= 2  # b[0] = [0.5, 0.5]                                                                                                
    for i in c:                                                                                                                   
        c[i] += b[0]  # c[0] = [0.5, 0.5]                                                                                         
                                                                                                                                  
test()                                                                                                                            
# Expect: [1. 1.] [0.5 0.5] [0.5 0.5]                                                                                             
# Result: [1. 1.] [0.5 0.5] [0.25 0.25]                                                                                           
print(a[0], b[0], c[0]) 
```
Note that the calculation steps in `test()` seem to be all relevant to reproducing the incorrect result. The program will produce correct result if you comment out any of them.

**Log/Screenshots**
On my Macbook Mbp, the CPU backends produces:

```
[Taichi] version 1.5.0, llvm 16.0.0git, commit 7b885c28, osx, python 3.10.10
[Taichi] Starting on arch=arm64
[1. 1.] [0.5 0.5] [0.5 0.5]
```

while the Vulkan backend produces:
```
[Taichi] version 1.5.0, llvm 16.0.0git, commit 7b885c28, osx, python 3.10.10
[Taichi] Starting on arch=vulkan
RHI Error: Potential non-conformant Vulkan implementation, enabling VK_KHR_portability_subset
[1. 1.] [0.5 0.5] [0.25 0.25]
```

**Additional comments**
The original issue was found by a forum user in the thread [here](https://forum.taichi-lang.cn/t/topic/4232).

### PR DESCRIPTION
**Pull request by ailzhang**
Fixes #7923 

### <samp>🤖 Generated by Copilot at 27ee72a</samp>

This pull request enhances the `offload` function to use memory and handle errors more efficiently, and fixes a global load demotion bug. It also adds a new test case to `tests/python/test_offload_cross.py` to verify the offloading logic for global temporaries.

### <samp>🤖 Generated by Copilot at 27ee72a</samp>

*  Prevent demoting global loads to local loads in `demotable_axis_load` ([link](https://github.com/taichi-dev/taichi/pull/7927/files?diff=unified&w=0#diff-d47b571f975c1002b8cb93634ac2a3d5f090f3fa9676ec3e0004c2ec4116ee21R20-R21))
*  Pass pointers instead of references or copies to the `local_to_global_offset` and `stmt_to_offloaded` maps in the `PromoteIntermediateToGlobalTmp` and `FixCrossOffloadReferences` passes ([link](https://github.com/taichi-dev/taichi/pull/7927/files?diff=unified&w=0#diff-d47b571f975c1002b8cb93634ac2a3d5f090f3fa9676ec3e0004c2ec4116ee21L445-R448), [link](https://github.com/taichi-dev/taichi/pull/7927/files?diff=unified&w=0#diff-d47b571f975c1002b8cb93634ac2a3d5f090f3fa9676ec3e0004c2ec4116ee21L464-R466), [link](https://github.com/taichi-dev/taichi/pull/7927/files?diff=unified&w=0#diff-d47b571f975c1002b8cb93634ac2a3d5f090f3fa9676ec3e0004c2ec4116ee21L470-R472), [link](https://github.com/taichi-dev/taichi/pull/7927/files?diff=unified&w=0#diff-d47b571f975c1002b8cb93634ac2a3d5f090f3fa9676ec3e0004c2ec4116ee21L480-R486), [link](https://github.com/taichi-dev/taichi/pull/7927/files?diff=unified&w=0#diff-d47b571f975c1002b8cb93634ac2a3d5f090f3fa9676ec3e0004c2ec4116ee21L663-R664), [link](https://github.com/taichi-dev/taichi/pull/7927/files?diff=unified&w=0#diff-d47b571f975c1002b8cb93634ac2a3d5f090f3fa9676ec3e0004c2ec4116ee21L673-R674), [link](https://github.com/taichi-dev/taichi/pull/7927/files?diff=unified&w=0#diff-d47b571f975c1002b8cb93634ac2a3d5f090f3fa9676ec3e0004c2ec4116ee21L786-R788))
*  Use the `at` method instead of the `[]` operator to access the `local_to_global_offset` map and avoid creating default entries ([link](https://github.com/taichi-dev/taichi/pull/7927/files?diff=unified&w=0#diff-d47b571f975c1002b8cb93634ac2a3d5f090f3fa9676ec3e0004c2ec4116ee21L457-R459), [link](https://github.com/taichi-dev/taichi/pull/7927/files?diff=unified&w=0#diff-d47b571f975c1002b8cb93634ac2a3d5f090f3fa9676ec3e0004c2ec4116ee21L502-R505), [link](https://github.com/taichi-dev/taichi/pull/7927/files?diff=unified&w=0#diff-d47b571f975c1002b8cb93634ac2a3d5f090f3fa9676ec3e0004c2ec4116ee21L517-R519), [link](https://github.com/taichi-dev/taichi/pull/7927/files?diff=unified&w=0#diff-d47b571f975c1002b8cb93634ac2a3d5f090f3fa9676ec3e0004c2ec4116ee21L533-R533), [link](https://github.com/taichi-dev/taichi/pull/7927/files?diff=unified&w=0#diff-d47b571f975c1002b8cb93634ac2a3d5f090f3fa9676ec3e0004c2ec4116ee21L626-R626))
*  Add a new test case in `test_offload_cross.py` to check the correctness of offloading intermediate values to global temporaries ([link](https://github.com/taichi-dev/taichi/pull/7927/files?diff=unified&w=0#diff-9fe47cc4660760632fda80fff05bd029da4d7e85a75429604feb5d23938b90ecR136-R156))

### CODE REVIEW

File: taichi/transforms/offload.cpp [hunk 1]
```diff
@@ -477,11 +479,11 @@ class FixCrossOffloadReferences : public BasicStmtVisitor {
  private:
   FixCrossOffloadReferences(
       const CompileConfig &config,
-      const StmtToOffsetMap &local_to_global_offset,
-      const std::unordered_map<Stmt *, Stmt *> &stmt_to_offloaded,
+      const StmtToOffsetMap *local_to_global_offset,
```
Comment (lin-hitonami) [inline taichi/transforms/offload.cpp:482]: can't we just pass the reference here just like `stmt_to_offloaded`?

Comment (ailzhang) [reply taichi/transforms/offload.cpp:482]: @lin-hitonami it's just trying to fail loudly if a temporary is passed in as const ref.

Comment (ailzhang) [reply taichi/transforms/offload.cpp:482]: eg. https://zpjiang.me/2020/01/20/const-reference-vs-pointer/

**Review by lin-hitonami — APPROVED** [review]
LGTM
