### PR TITLE
[bug] [gui] Use lower case for Win32 key events to unify with X11

### LINKED ISSUE #1138: [GUI] cannot get keyboard events
**Describe the bug**
GUI could not make any reaction after I press any key . (I first encounter at example/keyboard )

**Log/Screenshots**
There is no such meaningful log to show . Directly give out my code to reproduce.

**To Reproduce**
my environment version :
* [OS] : win10
* [Python] : 3.7.3
* [Taichi] : 0.6.7

my simple test code :
```
import taichi as ti

x, y = 0.5, 0.5
gui = ti.GUI("event test")
while True :
    while gui.get_event(ti.GUI.PRESS):
        print("press key : {}".format(gui.event.key)) 

    if gui.is_pressed(ti.GUI.LMB , ti.GUI.RMB):
        x, y = gui.get_cursor_pos()
    gui.circle((x,y) , radius= 8)
    gui.show()
```
1. start running , and trigger any click event (LMB or RMB)
2. we can see that print correctly
3. but once we press any key 
4. there is no log 
5. **GUI cannot make reactions anymore , to neither clicking nor pressing keys** 

the example logs below : 
```
[Taichi] mode=release
[Taichi] version 0.6.7, supported archs: [cpu, cuda, opengl], commit ca4d9dda, python 3.7.3

 *******************************************
 **     Taichi Programming Language       **
 *******************************************

[Taichi] mode=release
[Taichi] version 0.6.7, supported archs: [cpu, cuda, opengl], commit ca4d9dda, python 3.7.3
press key : LMB
press key : LMB
press key : RMB
press key : RMB
press key : RMB
press key : LMB # ( and then I pressed any key )

>>> Running time: 10.72s 
```

PS. It looks like that ``` self.has_key_event() ``` ( in ``` gui.py , line 182 ``` ) always returns false  after the problem occurs ...

### PR DESCRIPTION
**Pull request by archibate**
Related issue = close #1138

Win32 seems to return upper case for keys, while OS X and X11 uses lower case, let's unify them. Btw, @k-ye do you find ASWD keys working well on OS X? (just run `examples/keyboard.py`)

[[Click here for the format server]](http://kun.csail.mit.edu:31415/)

### CODE REVIEW

File: taichi/gui/win32.cpp [hunk 1]
```diff
@@ -53,7 +53,7 @@ static std::string lookup_keysym(WPARAM wParam, LPARAM lParam) {
       if (VK_F1 <= key && key <= VK_F12)
         return fmt::format("F{}", key - VK_F1);
       else if (isascii(key))
-        return std::string(1, key);
+        return std::string(1, ::tolower(key));
```
Comment (yuanming-hu) [inline taichi/gui/win32.cpp:56]: `::tolower` seems to be the C legacy function. Could you `#include <cctype>` and use `std::tolower` instead?

Comment (archibate) [reply taichi/gui/win32.cpp]: FYI the `isascii` above is also a C legacy function..
Also note that I found the *modern-featured-fasion-advanced-highly-superior* `<cctype>` says:
```
namespace std
{
  using ::isalnum;
  using ::isalpha;
  using ::iscntrl;
  using ::isdigit;
  using ::isgraph;
  using ::islower;
  using ::isprint;
  using ::ispunct;
  using ::isspace;
  using ::isupper;
  using ::isxdigit;
  using ::tolower;
  using ::toupper;
} // namespace std
```
cctype = copy from ctype :rofl:

**Comment by archibate** [comment]
Great, sleepy now, feel free to merge this ouo if AppVeyor shows passing.
