### PR TITLE
[misc] Improve type checking error messages

### LINKED ISSUE #793: Strange x86 codegen exception
**Describe the bug**
I was attempting to compute utilization of different arrays in my code and I ran into a weird compilation issue.
Trying to assign to multiple single-element buffers from a scalar variable modified in multiple loops causes a codegen exception.

**To Reproduce**
```python
import taichi as ti
ti.init(arch=ti.x64)

v = ti.var(ti.i32, 100)

a_count = ti.var(ti.i32, ())
b_count = ti.var(ti.i32, ())

@ti.kernel
def test():
    count = 0
    for i in v:
        count += 1
    a_count[None] = count
    
    # without the following lines, this program works.
    # with them, however, compilation fails.
    count = 0
    for i in v:
        count += 1
    b_count[None] = count

test()
```

The error is:
```
[I 04/15/20 14:08:33.701] [llvm_context.cpp:get_data_type@90] generic
[E 04/15/20 14:08:33.701] [llvm_context.cpp:get_data_type@91] Not supported.
```
followed by a stacktrace that ends with `taichi::lang::TaichiLLVMContext::get_data_type(taichi::lang::DataType)`.

### PR DESCRIPTION
**Pull request by yuanming-hu**
No rush on reviewing this - just some random modifications while trying to fix #793 

[[Click here for the format server]](http://kun.csail.mit.edu:31415/)

### CODE REVIEW

File: taichi/common/interface.h [hunk 1]
```diff
@@ -176,7 +176,7 @@ class InterfaceHolder {
              implementation_factories.end();                                  \
     }                                                                         \
     void remove(const std::string &alias) override {                          \
-      assert_info(has(alias),                                                 \
+      TI_ASSERT_INFO(has(alias),                                                 \
                   std::string("Implemetation ") + alias + " not found!");     \
       implementation_factories.erase(alias);                                  \
     }                                                                         \
```
Comment (xumingkuan) [inline taichi/common/interface.h:182]: The `\` on the right is not aligned... Will auto-format resolve this?

File: taichi/transforms/type_check.cpp [hunk 2]
```diff
@@ -414,10 +408,6 @@ namespace irpass {
 void typecheck(IRNode *root) {
   analysis::check_fields_registered(root);
   TypeCheck::run(root);
-  //  if (root->is<Block>() && root->as<Block>()->parent == nullptr) {
-  //    fix_block_parents(root); // hot fix
-  //    verify(root);
-  //  }
```
Comment (xumingkuan) [inline taichi/transforms/type_check.cpp:420]: Maybe I should start working on #739?

Comment (yuanming-hu) [reply taichi/transforms/type_check.cpp:420]: Sounds good!

File: taichi/common/interface.h (hunk 1 above)
Comment (yuanming-hu) [reply taichi/common/interface.h]: You are right - auto-formatting is our friend...

File: taichi/transforms/type_check.cpp (hunk 2 above)
Comment (yuanming-hu) [reply taichi/transforms/type_check.cpp:420]: (Sorry I didn't realize these comments are left there on purpose...)

**Comment by xumingkuan** [comment]
`TI_ASSERT(x)` with `x` containing `{}` fails now...

**Comment by yuanming-hu** [comment]
Is there an easy way to fix this? If no then I would say it will be easier if we do not use lamdas in `TI_ASSERT`...

**Comment by xumingkuan** [comment]
No, I think, as long as we're using `SPD_AUGMENTED_LOG`. It makes sense to me to not use lambdas in `TI_ASSERT`.
