### PR TITLE
[opengl] Fix unwanted "used.int64_t = true" in KernelReturnStmt

### LINKED ISSUE #1001: [Examples] mpm88.py not working
**Describe the bug**
The mpm88.py example does not work on my computer.

**Taichi Version**
0.6.4

**Log/Screenshots**
```
[Taichi] mode=release
[Taichi] version 0.6.4, supported archs: [cpu, opengl], commit 562e1f11, python 3.8.1
[E 05/17/20 10:43:29.709] [opengl_api.cpp:taichi::lang::opengl::GLShader::compile@100] [glsl] error while compiling shader:
  1 #version 430 core
  2 #extension GL_ARB_compute_shader: enable
  3 precision highp float;
  4 layout(packed, binding = 6) buffer runtime { int _rand_state_; };
  5 layout(packed, binding = 0) buffer data_i32 { int _data_i32_[]; };
  6 layout(packed, binding = 0) buffer data_f32 { float _data_f32_[]; };
  7 layout(packed, binding = 0) buffer data_f64 { double _data_f64_[]; };
  8 layout(packed, binding = 0) buffer data_i64 { int64_t _data_i64_[]; };
  9 layout(packed, binding = 1) buffer args_i32 { int _args_i32_[]; };
 10 layout(packed, binding = 1) buffer args_f32 { float _args_f32_[]; };
 11 layout(packed, binding = 1) buffer args_f64 { double _args_f64_[]; };
 12 layout(packed, binding = 1) buffer args_i64 { int64_t _args_i64_[]; };
 13
 14 void jit_evaluator_00()
 15 { // serial
 16   int B = _args_i32_[0 << 1];
 17   float C = float(B);
 18   _args_f32_[0] = C;
 19 }
 20
 21 void main()
 22 {
 23   jit_evaluator_00();
 24 }
 25 layout(local_size_x = 1 /* 1, 1 */, local_size_y = 1, local_size_z = 1) in;

Compute shader failed to compile with the following errors:
ERROR: 0:8: error(#132) Syntax error: "int64_t" parse error
ERROR: error(#273) 1 compilation errors.  No code generated




[38;2;255;000;255m***********************************
[0m[38;2;255;000;255m* Taichi Compiler Stack Traceback *
[0m[38;2;255;000;255m***********************************
[0m[38;2;255;000;255m0x7ffcf2d049f1: [0m[38;2;255;000;000mtaichi::create_instance<taichi::Benchmark>[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ffcf2b7695a: [0m[38;2;255;000;000mtaichi::create_instance<taichi::Benchmark>[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ffcf2e4c34b: [0m[38;2;255;000;000mtaichi::create_instance<taichi::Benchmark>[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ffcf2e49b44: [0m[38;2;255;000;000mtaichi::create_instance<taichi::Benchmark>[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ffcf2e4b4fc: [0m[38;2;255;000;000mtaichi::create_instance<taichi::Benchmark>[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ffcf2e3cccd: [0m[38;2;255;000;000mtaichi::create_instance<taichi::Benchmark>[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ffcf2e44807: [0m[38;2;255;000;000mtaichi::create_instance<taichi::Benchmark>[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ffcf2e40ede: [0m[38;2;255;000;000mtaichi::create_instance<taichi::Benchmark>[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ffcf2e3bcca: [0m[38;2;255;000;000mtaichi::create_instance<taichi::Benchmark>[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ffcf2e3b868: [0m[38;2;255;000;000mtaichi::create_instance<taichi::Benchmark>[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ffcf2c55805: [0m[38;2;255;000;000mtaichi::create_instance<taichi::Benchmark>[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ffcf2c46a86: [0m[38;2;255;000;000mtaichi::create_instance<taichi::Benchmark>[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ffcf2c468e3: [0m[38;2;255;000;000mtaichi::create_instance<taichi::Benchmark>[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ffcf2d0e0e1: [0m[38;2;255;000;000mtaichi::create_instance<taichi::Benchmark>[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ffcf2bdd68b: [0m[38;2;255;000;000mtaichi::create_instance<taichi::Benchmark>[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ffcf2bdd68b: [0m[38;2;255;000;000mtaichi::create_instance<taichi::Benchmark>[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ffcf2d0dadd: [0m[38;2;255;000;000mtaichi::create_instance<taichi::Benchmark>[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ffcf2d0cfd1: [0m[38;2;255;000;000mtaichi::create_instance<taichi::Benchmark>[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ffcf2d5519d: [0m[38;2;255;000;000mtaichi::create_instance<taichi::Benchmark>[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ffcf2d0ba8a: [0m[38;2;255;000;000mtaichi::create_instance<taichi::Benchmark>[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ffcf2e3e224: [0m[38;2;255;000;000mtaichi::create_instance<taichi::Benchmark>[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ffcf2e3b85d: [0m[38;2;255;000;000mtaichi::create_instance<taichi::Benchmark>[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ffcf2c55805: [0m[38;2;255;000;000mtaichi::create_instance<taichi::Benchmark>[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ffcf2c46a86: [0m[38;2;255;000;000mtaichi::create_instance<taichi::Benchmark>[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ffcf2c468e3: [0m[38;2;255;000;000mtaichi::create_instance<taichi::Benchmark>[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ffcf2cacee2: [0m[38;2;255;000;000mtaichi::create_instance<taichi::Benchmark>[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ffcf2c60106: [0m[38;2;255;000;000mtaichi::create_instance<taichi::Benchmark>[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ffcf2b5ff33: [0m[38;2;255;000;000mtaichi::create_instance<taichi::Benchmark>[0m[38;2;255;000;255m in taichi_core.pyd
[0m[38;2;255;000;255m0x7ffcfc3a27b4: [0m[38;2;255;000;000mPyCFunction_Call[0m[38;2;255;000;255m in python38.dll
[0m[38;2;255;000;255m0x7ffcfc3af9ec: [0m[38;2;255;000;000mPyObject_MakeTpCall[0m[38;2;255;000;255m in python38.dll
[0m[38;2;255;000;255m0x7ffcfc4b5b1d: [0m[38;2;255;000;000mPy_FatalError[0m[38;2;255;000;255m in python38.dll
[0m[38;2;255;000;255m0x7ffcfc379156: [0m[38;2;255;000;000mPyVectorcall_Call[0m[38;2;255;000;255m in python38.dll
[0m[38;2;255;000;255m0x7ffcfc3c9279: [0m[38;2;255;000;000mPyObject_Call[0m[38;2;255;000;255m in python38.dll
[0m[38;2;255;000;255m0x7ffcfc4dc239: [0m[38;2;255;000;000mPy_FatalError[0m[38;2;255;000;255m in python38.dll
[0m[38;2;255;000;255m0x7ffcfc3b4e5d: [0m[38;2;255;000;000mPy_CheckFunctionResult[0m[38;2;255;000;255m in python38.dll
[0m[38;2;255;000;255m0x7ffcfc3b5def: [0m[38;2;255;000;000mPyEval_EvalFrameDefault[0m[38;2;255;000;255m in python38.dll
[0m[38;2;255;000;255m0x7ffcfc3b17c8: [0m[38;2;255;000;000mPyEval_EvalCodeWithName[0m[38;2;255;000;255m in python38.dll
[0m[38;2;255;000;255m0x7ffcfc3b331f: [0m[38;2;255;000;000mPyFunction_Vectorcall[0m[38;2;255;000;255m in python38.dll
[0m[38;2;255;000;255m0x7ffcfc379156: [0m[38;2;255;000;000mPyVectorcall_Call[0m[38;2;255;000;255m in python38.dll
[0m[38;2;255;000;255m0x7ffcfc378fe7: [0m[38;2;255;000;000mPyNumber_Long[0m[38;2;255;000;255m in python38.dll
[0m[38;2;255;000;255m0x7ffcfc3b70a0: [0m[38;2;255;000;000mPyEval_EvalFrameDefault[0m[38;2;255;000;255m in python38.dll
[0m[38;2;255;000;255m0x7ffcfc3b17c8: [0m[38;2;255;000;000mPyEval_EvalCodeWithName[0m[38;2;255;000;255m in python38.dll
[0m[38;2;255;000;255m0x7ffcfc3b331f: [0m[38;2;255;000;000mPyFunction_Vectorcall[0m[38;2;255;000;255m in python38.dll
[0m[38;2;255;000;255m0x7ffcfc3c97b4: [0m[38;2;255;000;000mPyObject_FastCallDict[0m[38;2;255;000;255m in python38.dll
[0m[38;2;255;000;255m0x7ffcfc4587a9: [0m[38;2;255;000;000mPyObject_Call_Prepend[0m[38;2;255;000;255m in python38.dll
[0m[38;2;255;000;255m0x7ffcfc458719: [0m[38;2;255;000;000mPyObject_SelfIter[0m[38;2;255;000;255m in python38.dll
[0m[38;2;255;000;255m0x7ffcfc379063: [0m[38;2;255;000;000mPyNumber_Long[0m[38;2;255;000;255m in python38.dll
[0m[38;2;255;000;255m0x7ffcfc3b70a0: [0m[38;2;255;000;000mPyEval_EvalFrameDefault[0m[38;2;255;000;255m in python38.dll
[0m[38;2;255;000;255m0x7ffcfc3b17c8: [0m[38;2;255;000;000mPyEval_EvalCodeWithName[0m[38;2;255;000;255m in python38.dll
[0m[38;2;255;000;255m0x7ffcfc3b4810: [0m[38;2;255;000;000mPy_CheckFunctionResult[0m[38;2;255;000;255m in python38.dll
[0m[38;2;255;000;255m0x7ffcfc3b5def: [0m[38;2;255;000;000mPyEval_EvalFrameDefault[0m[38;2;255;000;255m in python38.dll
[0m[38;2;255;000;255m0x7ffcfc3b17c8: [0m[38;2;255;000;000mPyEval_EvalCodeWithName[0m[38;2;255;000;255m in python38.dll
[0m[38;2;255;000;255m0x7ffcfc3b4810: [0m[38;2;255;000;000mPy_CheckFunctionResult[0m[38;2;255;000;255m in python38.dll
[0m[38;2;255;000;255m0x7ffcfc3b5f82: [0m[38;2;255;000;000mPyEval_EvalFrameDefault[0m[38;2;255;000;255m in python38.dll
[0m[38;2;255;000;255m0x7ffcfc3b17c8: [0m[38;2;255;000;000mPyEval_EvalCodeWithName[0m[38;2;255;000;255m in python38.dll
[0m[38;2;255;000;255m0x7ffcfc3ffbe7: [0m[38;2;255;000;000mPyEval_EvalCodeEx[0m[38;2;255;000;255m in python38.dll
[0m[38;2;255;000;255m0x7ffcfc3ffb45: [0m[38;2;255;000;000mPyEval_EvalCode[0m[38;2;255;000;255m in python38.dll
[0m[38;2;255;000;255m0x7ffcfc3fef76: [0m[38;2;255;000;000mPyArena_New[0m[38;2;255;000;255m in python38.dll
[0m[38;2;255;000;255m0x7ffcfc3fef05: [0m[38;2;255;000;000mPyArena_New[0m[38;2;255;000;255m in python38.dll
[0m[38;2;255;000;255m0x7ffcfc4809e4: [0m[38;2;255;000;000mPyRun_FileExFlags[0m[38;2;255;000;255m in python38.dll
[0m[38;2;255;000;255m0x7ffcfc480787: [0m[38;2;255;000;000mPyRun_SimpleFileExFlags[0m[38;2;255;000;255m in python38.dll
[0m[38;2;255;000;255m0x7ffcfc54228b: [0m[38;2;255;000;000mPyRun_AnyFileExFlags[0m[38;2;255;000;255m in python38.dll
[0m[38;2;255;000;255m0x7ffcfc4d40a5: [0m[38;2;255;000;000mPy_FatalError[0m[38;2;255;000;255m in python38.dll
[0m[38;2;255;000;255m0x7ffcfc425ae4: [0m[38;2;255;000;000mPy_RunMain[0m[38;2;255;000;255m in python38.dll
[0m[38;2;255;000;255m0x7ffcfc42596d: [0m[38;2;255;000;000mPy_RunMain[0m[38;2;255;000;255m in python38.dll
[0m[38;2;255;000;255m0x7ffcfc4249dd: [0m[38;2;255;000;000mPy_Main[0m[38;2;255;000;255m in python38.dll
[0m[38;2;255;000;255m0x7ff7a92f1258: [0m[38;2;255;000;000mUnknown Function[0m[38;2;255;000;255m in python.exe
[0m[38;2;255;000;255m0x7ffd45117bd4: [0m[38;2;255;000;000mBaseThreadInitThunk[0m[38;2;255;000;255m in KERNEL32.DLL
[0m[38;2;255;000;255m0x7ffd46bcced1: [0m[38;2;255;000;000mRtlUserThreadStart[0m[38;2;255;000;255m in ntdll.dll
[0mTraceback (most recent call last):
  File "mpm88.py", line 86, in <module>
    grid_v.fill([0, 0])
  File "C:\Program Project\Python 3.8.1\lib\site-packages\taichi\lang\matrix.py", line 502, in fill
    fill_matrix(self, val)
  File "C:\Program Project\Python 3.8.1\lib\site-packages\taichi\lang\kernel.py", line 500, in wrapped
    return primal(*args, **kwargs)
  File "C:\Program Project\Python 3.8.1\lib\site-packages\taichi\lang\kernel.py", line 431, in __call__
    return self.compiled_functions[key](*args)
  File "C:\Program Project\Python 3.8.1\lib\site-packages\taichi\lang\kernel.py", line 395, in func__
    t_kernel()
RuntimeError: [opengl_api.cpp:taichi::lang::opengl::GLShader::compile@100] [glsl] error while compiling shader:
  1 #version 430 core
  2 #extension GL_ARB_compute_shader: enable
  3 precision highp float;
  4 layout(packed, binding = 6) buffer runtime { int _rand_state_; };
  5 layout(packed, binding = 0) buffer data_i32 { int _data_i32_[]; };
  6 layout(packed, binding = 0) buffer data_f32 { float _data_f32_[]; };
  7 layout(packed, binding = 0) buffer data_f64 { double _data_f64_[]; };
  8 layout(packed, binding = 0) buffer data_i64 { int64_t _data_i64_[]; };
  9 layout(packed, binding = 1) buffer args_i32 { int _args_i32_[]; };
 10 layout(packed, binding = 1) buffer args_f32 { float _args_f32_[]; };
 11 layout(packed, binding = 1) buffer args_f64 { double _args_f64_[]; };
 12 layout(packed, binding = 1) buffer args_i64 { int64_t _args_i64_[]; };
 13
 14 void jit_evaluator_00()
 15 { // serial
 16   int B = _args_i32_[0 << 1];
 17   float C = float(B);
 18   _args_f32_[0] = C;
 19 }
 20
 21 void main()
 22 {
 23   jit_evaluator_00();
 24 }
 25 layout(local_size_x = 1 /* 1, 1 */, local_size_y = 1, local_size_z = 1) in;

Compute shader failed to compile with the following errors:
ERROR: 0:8: error(#132) Syntax error: "int64_t" parse error
ERROR: error(#273) 1 compilation errors.  No code generated
```

**To Reproduce**
Run the example examples\mpm88.py

**System Information**
Operating system: Windows-10-10.0.18362-SP0 64 Bits
Graphics card: AMD Radeon HD 7560D ATI Technologies Inc. 4.5.13399 Core Profile Context 15.201.1151.1008

### PR DESCRIPTION
**Pull request by archibate**
Related issue = close #1001

[[Click here for the format server]](http://kun.csail.mit.edu:31415/)

### CODE REVIEW

File: taichi/backends/opengl/codegen_opengl.cpp [hunk 1]
```diff
@@ -92,6 +92,12 @@ class KernelGen : public IRVisitor {
     return opengl::opengl_data_type_name(dt);
   }
 
+  std::string opengl_data_type_short_name(DataType dt) {  // catch & forward
+    if (dt == DataType::i64)
```
Comment (yuanming-hu) [inline taichi/backends/opengl/codegen_opengl.cpp:96]:
```suggestion
  std::string opengl_data_type_short_name(DataType dt) {
    // Note that this function not only returns the corresponding data type,
    // but also **records** the usage of `i64`.
    if (dt == DataType::i64)
```
