### PR TITLE
[gui] [error] [linux] Better error message when X display not available

### LINKED ISSUE #1551: [GUI] Initializing GUI fails on Ubuntu 16.04
**Describe the bug**
os: ubuntu.16.04
tiachi: f1967f62e8, mode=development
also repeat by pip install

**To Reproduce**
python3 taichi_logo.py

**Log/Screenshots**
(base) sensetime@sensetime:~/src/taichi/examples$ python3 taichi_logo.py 
[Taichi] mode=development
[Taichi] preparing sandbox at /tmp/taichi-zycf1d1o
[Taichi] <dev mode>, llvm 10.0.0, commit f1967f62, python 3.7.4
[E 07/21/20 17:27:08.147] Received signal 11 (Segmentation fault)

\***********************************
\* Taichi Compiler Stack Traceback *
\***********************************
/tmp/taichi-zycf1d1o/taichi_core.so: taichi::Logger::error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)
/tmp/taichi-zycf1d1o/taichi_core.so: taichi::signal_handler(int)
/lib/x86_64-linux-gnu/libc.so.6(+0x354c0) [0x7f0fa2ee34c0]
/tmp/taichi-zycf1d1o/taichi_core.so: taichi::GUI::create_window()
/tmp/taichi-zycf1d1o/taichi_core.so: taichi::GUI::GUI(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int, bool)
/tmp/taichi-zycf1d1o/taichi_core.so(+0x93171c) [0x7f0f90e2a71c]
/tmp/taichi-zycf1d1o/taichi_core.so(+0x931617) [0x7f0f90e2a617]
/tmp/taichi-zycf1d1o/taichi_core.so(+0x891830) [0x7f0f90d8a830]
python3(_PyMethodDef_RawFastCallDict+0x24d) [0x56452053b63d]
python3(_PyCFunction_FastCallDict+0x21) [0x56452053b7c1]
python3(_PyObject_Call_Prepend+0x63) [0x564520539e53]
python3(PyObject_Call+0x6e) [0x56452052cdbe]
python3(+0x9e214) [0x5645204a4214]
python3(_PyObject_FastCallKeywords+0x128) [0x564520572588]
python3(_PyEval_EvalFrameDefault+0x52f8) [0x5645205d66e8]
python3(_PyEval_EvalCodeWithName+0x2f9) [0x56452051a539]
python3(_PyFunction_FastCallDict+0x1d5) [0x56452051b635]
python3(_PyObject_Call_Prepend+0x63) [0x564520539e53]
python3(+0x16b97a) [0x56452057197a]
python3(_PyObject_FastCallKeywords+0x128) [0x564520572588]
python3(_PyEval_EvalFrameDefault+0x52f8) [0x5645205d66e8]
python3(_PyEval_EvalCodeWithName+0x2f9) [0x56452051a539]
python3(PyEval_EvalCodeEx+0x44) [0x56452051b424]
python3(PyEval_EvalCode+0x1c) [0x56452051b44c]
python3(+0x22ab74) [0x564520630b74]
python3(PyRun_FileExFlags+0xa1) [0x56452063aeb1]
python3(PyRun_SimpleFileExFlags+0x1c3) [0x56452063b0a3]
python3(+0x236195) [0x56452063c195]
python3(_Py_UnixMain+0x3c) [0x56452063c2bc]
/lib/x86_64-linux-gnu/libc.so.6: __libc_start_main
python3(+0x1db062) [0x5645205e1062]

**If you have local commits (e.g. compile fixes before you reproduce the bug), please make sure you first make a PR to fix the build errors and then report the bug.**
no local change

### PR DESCRIPTION
**Pull request by archibate**
Related issue = close #1551

[[Click here for the format server]](http://kun.csail.mit.edu:31415/)

----

### CODE REVIEW

File: taichi/gui/x11.cpp [hunk 1]
```diff
@@ -133,10 +133,15 @@ void GUI::process_event() {
 
 void GUI::create_window() {
   display = XOpenDisplay(nullptr);
+  TI_ASSERT_INFO(display,
+                 "Taichi fails to create a window."
```
Comment (yuanming-hu) [inline taichi/gui/x11.cpp:137]:
```suggestion
                 "Taichi failed to create a window."
```
