### PR TITLE
[vulkan] Fix command serial ordering & uses less queue submits

### LINKED ISSUE #3791: [Vulkan] `ti.sync()` changes program behavior on Vulkan
Example of when `ti.sync()` changes program behavior on Vulkan: #3790. In this example, the program only behaves correctly when the `ti.sync()` is added. 

On vulkan, we aggressively batch consecutive kernel launches into a single command buffer. We probably need to add a buffer_barrier or something between consecutive compute dispatches. I will investigate this.

### PR DESCRIPTION
**Pull request by bobcao3**
Fixes #3791

### CODE REVIEW

File: taichi/backends/vulkan/runtime.cpp [hunk 1]
```diff
@@ -411,26 +407,46 @@ VkRuntime::KernelHandle VkRuntime::register_taichi_kernel(
...
+  if (ti_kernel->get_ctx_buffer_size()) {
+    ctx_buffer = device_->allocate_memory_unique(
+        {ti_kernel->get_ctx_buffer_size(),
+           /*host_write=*/true, /*host_read=*/false,
+           /*export_sharing=*/false, AllocUsage::Storage});
+    ctx_buffer_host = device_->allocate_memory_unique(
+        {ti_kernel->get_ctx_buffer_size(),
+           /*host_write=*/false, /*host_read=*/true,
+           /*export_sharing=*/false, AllocUsage::Storage});
+  }
```
Comment (AmesingFlank) [inline taichi/backends/vulkan/runtime.cpp:422]: r we creating new buffers every time we launch a kernel?

Comment (bobcao3) [reply taichi/backends/vulkan/runtime.cpp:422]: yes

Comment (AmesingFlank) [reply taichi/backends/vulkan/runtime.cpp]: .. that can't be good

Comment (bobcao3) [reply taichi/backends/vulkan/runtime.cpp]: It is fine, it is actually faster than before

Comment (AmesingFlank) [reply taichi/backends/vulkan/runtime.cpp]: be that as it may, we should still at least try to reuse some of these buffers. It is fast now because VMA is doing a superb job, but what if we want to unify the runtime code for different backends?

Comment (bobcao3) [reply taichi/backends/vulkan/runtime.cpp]: We can't reuse them until we know for sure they are done. A better solution is a ring buffer, but in terms of memory usage it's the same.

Comment (bobcao3) [reply taichi/backends/vulkan/runtime.cpp]: Also for DX11 and OpenGL this is going to be faster than a ring buffer because the drivers know for sure there isn't overlap and is free to use them async.

Comment (bobcao3) [reply taichi/backends/vulkan/runtime.cpp]: So in the end only maybe Vulkan / DX12 / and Metal will benefit from a ring buffer, and all of these requires a robust memory allocator anyways.

Comment (AmesingFlank) [reply taichi/backends/vulkan/runtime.cpp]: What about the overhead of allocating buffers on DX and GL? Are we confident that the performance gain from having things async outweighs these overheads?

Comment (bobcao3) [reply taichi/backends/vulkan/runtime.cpp]: If it's buffer reuse it should be implemented in the allocator instead of the runtime

Comment (bobcao3) [reply taichi/backends/vulkan/runtime.cpp]: Let's do the naive way for now, we can figure out a better way later

File: taichi/backends/vulkan/runtime.cpp [hunk 2]
```diff
@@ -293,15 +286,14 @@ size_t CompiledTaichiKernel::num_pipelines() const {
...
+size_t CompiledTaichiKernel::get_ctx_buffer_size() const {
+  return ctx_buffer_size_;
 }
 
-DeviceAllocation *CompiledTaichiKernel::ctx_buffer_host() const {
-  return ctx_buffer_host_.get();
-}
-
-void CompiledTaichiKernel::command_list(CommandList *cmdlist) const {
+void CompiledTaichiKernel::command_list(
```
Comment (k-ye) [inline taichi/backends/vulkan/runtime.cpp:293]: Out of curiosity, what does the function name `command_list` mean here, `run_command_list`?

File: taichi/backends/vulkan/runtime.cpp [hunk 3]
```diff
@@ -411,26 +408,46 @@ VkRuntime::KernelHandle VkRuntime::register_taichi_kernel(
 
 void VkRuntime::launch_kernel(KernelHandle handle, RuntimeContext *host_ctx) {
   auto *ti_kernel = ti_kernels_[handle.id_].get();
+
+  std::unique_ptr<DeviceAllocationGuard> ctx_buffer_host, ctx_buffer;
```
Comment (k-ye) [inline taichi/backends/vulkan/runtime.cpp:412]:
```suggestion
  std::unique_ptr<DeviceAllocationGuard> ctx_buffer_host{nullptr}, ctx_buffer{nullptr};
```

File: taichi/backends/vulkan/runtime.cpp [hunk 4]
```diff
@@ -411,26 +408,46 @@ VkRuntime::KernelHandle VkRuntime::register_taichi_kernel(
...
+
+  if (ti_kernel->get_ctx_buffer_size()) {
+    ctx_buffer = device_->allocate_memory_unique(
```
Comment (k-ye) [inline taichi/backends/vulkan/runtime.cpp:415]: Would this result in memory fragmentation? Or the VMA should take care of it?

File: taichi/backends/vulkan/runtime.cpp (hunk 2 above)
Comment (bobcao3) [reply taichi/backends/vulkan/runtime.cpp:293]: This means record command list

File: taichi/backends/vulkan/runtime.cpp (hunk 4 above)
Comment (bobcao3) [reply taichi/backends/vulkan/runtime.cpp:415]: It would, let's do the naive one for now until we kick ext arr out of context buffer and add a ring buffer

File: taichi/backends/vulkan/runtime.cpp (hunk 2 above)
Comment (k-ye) [reply taichi/backends/vulkan/runtime.cpp:293]: nit: Can we just rename it to `record_command_list` then :-) ?

File: taichi/backends/vulkan/runtime.cpp (hunk 4 above)
Comment (k-ye) [reply taichi/backends/vulkan/runtime.cpp:416]: SG

**Review by k-ye — APPROVED** [review]
LGTM!

**Review by ailzhang — APPROVED** [review]
Nice work! Thanks!
